module Guide.Beginner where

beginnerGuide :: String
beginnerGuide = unlines
    [ "# VGA Planets Beginner's Complete Guide"
    , ""
    , "## Welcome to VGA Planets"
    , ""
    , "### What is VGA Planets?"
    , "VGA Planets is a complex turn-based space strategy game where:"
    , "- **11 Players** compete for galactic domination"
    , "- **Each Race** has unique abilities and ship designs"
    , "- **Turn-Based**: All players submit moves, then turns process simultaneously"
    , "- **Strategic Depth**: Economics, diplomacy, technology, and warfare all matter"
    , ""
    , "### Game Basics"
    , "- **Turns**: Games typically run 50-100+ turns"
    , "- **Turn Schedule**: Usually 2-3 days per turn"
    , "- **Simultaneous**: All players move at the same time"
    , "- **Information**: You only see what your ships/planets detect"
    , ""
    , "## Your First Turn"
    , ""
    , "### Starting Position"
    , "You begin with:"
    , "- **1 Planet**: Your homeworld with basic infrastructure"
    , "- **1 Starbase**: For ship construction and tech research"
    , "- **1 Ship**: Usually a small freighter or escort"
    , "- **Basic Resources**: Some money, minerals, and supplies"
    , ""
    , "### Essential First Turn Actions"
    , ""
    , "#### 1. Explore Your Homeworld"
    , "- **Check Resources**: Note mineral densities and climate"
    , "- **Review Population**: Colonists and native races"
    , "- **Set Taxes**: Start with 5-10% colonist tax, 15-20% native tax"
    , "- **Build Infrastructure**: Add some mines and factories"
    , ""
    , "#### 2. Plan Ship Movement"
    , "- **Scout Nearby**: Send your ship to explore adjacent areas"
    , "- **Fuel Management**: Ensure ship has enough fuel"
    , "- **Set Mission**: Use 'Explore' mission to reveal planet details"
    , "- **Friendly Code**: Set a recognizable code (like your initials)"
    , ""
    , "#### 3. Starbase Operations"
    , "- **Check Tech Levels**: All start at 1"
    , "- **Plan Upgrades**: Decide which tech to advance first"
    , "- **Review Ship Designs**: See what you can build"
    , "- **Start Building**: Consider building a scout or freighter"
    , ""
    , "#### 4. Set Next Turn Goals"
    , "- **Exploration**: Find 3-5 nearby planets"
    , "- **Colonization**: Identify good planets to colonize"
    , "- **Resource Development**: Plan mining and factory expansion"
    , "- **Defense**: Consider basic security needs"
    , ""
    , "## Early Game Strategy (Turns 1-20)"
    , ""
    , "### Exploration Phase"
    , "- **Priority**: Find colonizable planets within 50-100 light years"
    , "- **Ship Types**: Use fast scouts for exploration"
    , "- **Coverage**: Explore in multiple directions"
    , "- **Documentation**: Keep notes on planet locations and properties"
    , ""
    , "### Colonization Priorities"
    , "Look for planets with:"
    , "- **Good Climate**: Temperature range suitable for your race"
    , "- **High Minerals**: Density 50+ in any mineral type"
    , "- **Useful Natives**: Races that provide bonuses"
    , "- **Strategic Location**: Between you and potential enemies"
    , ""
    , "### Economic Development"
    , "- **Mining First**: Build mines before factories"
    , "- **Population Growth**: Keep happiness 40-70 for growth"
    , "- **Balanced Development**: Don't neglect any planet completely"
    , "- **Supply Production**: Build factories for ship construction"
    , ""
    , "### Technology Advancement"
    , "**Recommended Tech Order:**"
    , "1. **Hull Tech 3-4**: Access to better ship designs"
    , "2. **Engine Tech 3-4**: More fuel-efficient engines"
    , "3. **Beam Tech 3-4**: Decent defensive weapons"
    , "4. **Torpedo Tech 3-4**: Basic offensive capability"
    , ""
    , "## Your Second Turn"
    , ""
    , "### Review Results"
    , "- **Check Messages**: Read host messages and any diplomacy"
    , "- **Ship Reports**: See what your ships discovered"
    , "- **Planet Growth**: Check population and production changes"
    , "- **Resource Status**: Monitor money, minerals, supplies"
    , ""
    , "### Expansion Activities"
    , "- **Continue Exploration**: Send ships to new areas"
    , "- **Start Colonization**: Send colonists to good planets"
    , "- **Build More Ships**: Construct scouts and freighters"
    , "- **Develop Infrastructure**: Add mines and factories"
    , ""
    , "### First Contact Preparation"
    , "- **Expect Contact**: Other players' ships will find you soon"
    , "- **Diplomatic Readiness**: Decide on initial diplomatic stance"
    , "- **Basic Defense**: Have some armed ships available"
    , "- **Intelligence**: Try to identify which races you've found"
    , ""
    , "## Common Beginner Mistakes"
    , ""
    , "### Economic Errors"
    , "- **Over-Taxation**: Killing happiness and stopping growth"
    , "- **Under-Development**: Not building enough infrastructure"
    , "- **Resource Imbalance**: Having too much of one resource"
    , "- **Poor Planning**: Not considering long-term needs"
    , ""
    , "### Military Mistakes"
    , "- **No Defense**: Leaving planets completely undefended"
    , "- **Over-Militarization**: Building warships too early"
    , "- **Poor Ship Design**: Using inappropriate weapons/engines"
    , "- **Fuel Management**: Running out of fuel far from home"
    , ""
    , "### Strategic Blunders"
    , "- **Isolation**: Not making any diplomatic contact"
    , "- **Aggression**: Attacking everyone you meet"
    , "- **Passivity**: Not expanding or developing"
    , "- **Information Neglect**: Not scouting or gathering intelligence"
    , ""
    , "## Race Selection for Beginners"
    , ""
    , "### Recommended Beginner Races"
    , ""
    , "#### 1. Solar Federation"
    , "- **Strengths**: Double tax income, good ships, forgiving economy"
    , "- **Weaknesses**: Reduced mining efficiency"
    , "- **Why Good**: Economic power compensates for mistakes"
    , ""
    , "#### 2. Fascist Empire"
    , "- **Strengths**: Good military, pillage ability, straightforward"
    , "- **Weaknesses**: Fewer economic bonuses"
    , "- **Why Good**: Clear military focus, good for learning combat"
    , ""
    , "#### 3. Robotic Imperium"
    , "- **Strengths**: Self-repairing ships, good production"
    , "- **Weaknesses**: Less exciting special abilities"
    , "- **Why Good**: Forgiving ships, steady development"
    , ""
    , "### Races to Avoid as Beginner"
    , "- **Lizards**: Require aggressive early play"
    , "- **Birds**: Complex cloaking and spy mechanics"
    , "- **Crystals**: Defensive specialists need game knowledge"
    , "- **Cyborg**: Complex assimilation and chunnel mechanics"
    , ""
    , "## Essential Interface Tips"
    , ""
    , "### Navigation"
    , "- **Starmap**: Learn to zoom and navigate efficiently"
    , "- **Ship Lists**: Use filters to find specific ships"
    , "- **Planet Lists**: Sort by different criteria"
    , "- **Messages**: Read all messages carefully"
    , ""
    , "### Turn Management"
    , "- **Save Often**: Use the save function frequently"
    , "- **Double-Check**: Review all orders before submitting"
    , "- **Time Management**: Don't rush your first few turns"
    , "- **Help System**: Use in-game help when confused"
    , ""
    , "## Diplomatic Basics"
    , ""
    , "### First Contact Protocol"
    , "- **Friendly Greeting**: Introduce yourself politely"
    , "- **Race Identification**: Ask what race they're playing"
    , "- **Peaceful Intentions**: Express desire for peaceful coexistence"
    , "- **Information Exchange**: Share basic non-sensitive information"
    , ""
    , "### Early Diplomacy"
    , "- **Non-Aggression Pacts**: Agree not to attack each other"
    , "- **Border Agreements**: Establish rough territorial boundaries"
    , "- **Trade Discussions**: Consider resource exchanges"
    , "- **Intelligence Sharing**: Share information about other players"
    , ""
    , "## Turn 3-10 Development"
    , ""
    , "### Consolidation"
    , "- **Secure Territory**: Establish control over 5-10 planets"
    , "- **Build Economy**: Develop mining and production"
    , "- **Tech Advancement**: Continue upgrading starbase tech"
    , "- **Fleet Building**: Start constructing proper warships"
    , ""
    , "### Preparation for Mid-Game"
    , "- **Alliance Building**: Form relationships with neighbors"
    , "- **Military Buildup**: Prepare for eventual conflicts"
    , "- **Economic Optimization**: Maximize resource production"
    , "- **Strategic Planning**: Identify long-term goals"
    , ""
    , "## Learning Resources"
    , ""
    , "### In-Game Learning"
    , "- **Help System**: Comprehensive documentation"
    , "- **VCR Analysis**: Study battle replays"
    , "- **Message History**: Learn from diplomatic exchanges"
    , "- **Statistics**: Monitor your progress over time"
    , ""
    , "### Community Resources"
    , "- **Forums**: Ask questions and read strategy discussions"
    , "- **Experienced Players**: Find mentors willing to help"
    , "- **Strategy Guides**: Read detailed race and tactic guides"
    , "- **Video Content**: Watch gameplay tutorials"
    , ""
    , "## Next Steps"
    , ""
    , "### After Your First Game"
    , "- **Analyze Performance**: What worked and what didn't?"
    , "- **Try Different Races**: Experience various play styles"
    , "- **Study Advanced Tactics**: Learn complex strategies"
    , "- **Join Community**: Participate in forums and discussions"
    , ""
    , "### Skill Development Path"
    , "1. **Master Basics**: Economics, exploration, colonization"
    , "2. **Learn Combat**: Ship design, tactics, fleet management"
    , "3. **Study Diplomacy**: Alliance building, negotiation"
    , "4. **Advanced Strategy**: Economic warfare, late-game tactics"
    , ""
    , "Welcome to the galaxy, Commander! May your first steps lead to"
    , "galactic domination!"
    ]