module Guide.Combat where

combatGuide :: String
combatGuide = unlines
    [ "# VGA Planets Combat Complete Guide"
    , ""
    , "## Combat Fundamentals"
    , ""
    , "### Combat Overview"
    , "Combat in VGA Planets is turn-based and occurs between:"
    , "- **Ship vs Ship**: Space battles between opposing fleets"
    , "- **Ship vs Planet**: Attacks on planetary defenses"
    , "- **Ship vs Starbase**: Assaults on orbital installations"
    , "- **Ground Combat**: Planetary invasion attempts"
    , ""
    , "### Visual Combat Replay (VCR)"
    , "Every combat generates a VCR that shows:"
    , "- **Battle Sequence**: Step-by-step combat resolution"
    , "- **Damage Application**: How damage affects each combatant"
    , "- **Battle Outcome**: Winner, casualties, and survivors"
    , "- **Tactical Analysis**: What happened and why"
    , ""
    , "## Ship-to-Ship Combat"
    , ""
    , "### Battle Sequence"
    , "Combat occurs in specific phases:"
    , "1. **Fighter Launch**: Carriers deploy fighter squadrons"
    , "2. **Fighter Attack**: Fighters engage enemy ships"
    , "3. **Torpedo Phase**: Ships fire torpedoes at enemy vessels"
    , "4. **Beam Combat**: Ships fire beam weapons"
    , "5. **Damage Resolution**: Apply damage to shields and hull"
    , "6. **Next Round**: Repeat until one side wins or retreats"
    , ""
    , "### Battle Positioning"
    , "Ship positioning affects combat effectiveness:"
    , "- **Left Side Advantage**: Better for carriers (fighters launch first)"
    , "- **Right Side Advantage**: Better for torpedo ships vs carriers"
    , "- **Mass Determination**: Lower battle value fights from right side"
    , "- **Battle Value**: Based on ship mass, weapons, and crew"
    , ""
    , "### Weapon Ranges"
    , "Different weapons have different effective ranges:"
    , "1. **Fighters**: Longest range, attack first"
    , "2. **Torpedoes**: Medium range, powerful damage"
    , "3. **Beam Weapons**: Short range, versatile"
    , ""
    , "## Damage System"
    , ""
    , "### Shield Mechanics"
    , "- **Shield Strength**: Absorbs damage before hull takes hits"
    , "- **Shield Regeneration**: Some races regenerate shields between battles"
    , "- **Shield Penetration**: Some weapons bypass shields partially"
    , "- **Shield Failure**: Depleted shields offer no protection"
    , ""
    , "### Hull Damage Effects"
    , "Hull damage reduces ship effectiveness:"
    , "- **0-20% Damage**: No performance penalty"
    , "- **21-50% Damage**: Reduced weapon accuracy and power"
    , "- **51-99% Damage**: Severely degraded performance"
    , "- **100% Damage**: Ship destroyed"
    , ""
    , "### Crew Casualties"
    , "- **Crew Kill Value**: Each weapon has crew kill rating"
    , "- **Shield Protection**: Shields protect crew from most damage"
    , "- **Direct Hits**: Unshielded ships suffer heavy crew losses"
    , "- **Ship Capture**: Ships with dead crew can be captured"
    , ""
    , "## Combat Tactics"
    , ""
    , "### Torpedo Ship Tactics"
    , "- **Mass Advantage**: Heavier ships have combat bonuses"
    , "- **Positioning**: Prefer right side vs carriers"
    , "- **Weapon Selection**: Mark 8 torpedoes for damage, Mark 4 for efficiency"
    , "- **Target Priority**: Focus on carriers and heavy combatants"
    , ""
    , "### Carrier Tactics"
    , "- **Fighter Advantage**: Fighters attack before other weapons"
    , "- **Left Side Bonus**: Carriers perform better from left position"
    , "- **Fighter Capacity**: More fighters = longer sustained combat"
    , "- **Screening**: Use escorts to protect carriers"
    , ""
    , "### Ship Capture Strategies"
    , "To capture rather than destroy enemy ships:"
    , "- **Gamma Bombs**: High crew kill, lower hull damage"
    , "- **Disruptor Beams**: Good crew kill to damage ratio"
    , "- **Boarding Parties**: Privateer special ability"
    , "- **Weakened Targets**: Attack damaged ships for easier capture"
    , ""
    , "## Racial Combat Abilities"
    , ""
    , "### Federation"
    , "- **Crew Bonus**: +50kT mass, +3 fighter bays, +25% shield regen"
    , "- **All Weapons Available**: Damaged weapons remain functional"
    , "- **Shield Regeneration**: Recover 25% shields between battles"
    , ""
    , "### Lizards"
    , "- **Lizard Crew**: Ships can take 150% damage before destruction"
    , "- **Damage Immunity**: Ignore first 50% damage to engines/weapons"
    , "- **Ground Combat**: 30:1 attack, 15:1 defense ratios"
    , ""
    , "### Birds"
    , "- **Cloaking**: Avoid detection and combat initiation"
    , "- **Super Spy**: Gather intelligence before attacking"
    , "- **Stealth Attacks**: Strike isolated or weakened targets"
    , ""
    , "### Fascists"
    , "- **Glory Device**: Self-destruct for massive area damage"
    , "- **Imperial Assault**: Enhanced ground combat capabilities"
    , "- **Aggressive Tactics**: Bonus damage in certain situations"
    , ""
    , "### Privateers"
    , "- **Boarding Parties**: Capture enemy ships instead of destroying"
    , "- **Rob Mission**: Steal money before combat"
    , "- **Economic Warfare**: Focus on capturing valuable vessels"
    , ""
    , "### Cyborg"
    , "- **Self Repair**: Automatic damage repair each turn"
    , "- **Assimilation**: Convert captured ships and planets"
    , "- **Technology Edge**: Advanced ship designs"
    , ""
    , "### Crystals"
    , "- **Web Mines**: Area denial and fleet immobilization"
    , "- **Desert Advantage**: Combat bonuses on desert planets"
    , "- **Defensive Specialists**: Excel at holding territory"
    , ""
    , "### Evil Empire"
    , "- **Dark Sense**: Detect and counter cloaked ships"
    , "- **Death Ray**: Destroy planetary populations"
    , "- **Anti-Stealth**: Specialized in fighting cloaking races"
    , ""
    , "### Robots"
    , "- **Self Repair**: Automatic hull repair capabilities"
    , "- **Industrial Might**: Large fleets through efficient production"
    , "- **Attrition Warfare**: Sustain longer campaigns"
    , ""
    , "### Rebels"
    , "- **Defensive Bonus**: Enhanced combat on owned planets"
    , "- **Guerrilla Tactics**: Bonus when fighting on home territory"
    , "- **Planetary Defense**: Strong defensive installations"
    , ""
    , "### Colonies"
    , "- **Cloaking Ability**: Stealth operations like Birds"
    , "- **Salvage Operations**: Recover materials from battles"
    , "- **Balanced Combat**: No major weaknesses or strengths"
    , ""
    , "## Planetary Combat"
    , ""
    , "### Defense Posts"
    , "- **Maximum**: 200 defense posts per planet"
    , "- **Combat Value**: Each post equals 1 fighter in combat"
    , "- **Construction**: Built like other planetary structures"
    , "- **Cost**: 10 Duranium, 1 Molybdenum, 10 supplies each"
    , ""
    , "### Starbase Defense"
    , "- **Base Fighters**: Up to 60 fighters stored at starbase"
    , "- **Beam Weapons**: Up to 20 beam weapons on starbase"
    , "- **Combined Defense**: Starbase + defense posts + orbiting ships"
    , "- **Mass Factor**: Starbase counts as 900kT in combat"
    , ""
    , "### Ground Assault"
    , "- **Clan Combat**: Attacking clans vs defending clans"
    , "- **Racial Modifiers**: Some races have ground combat bonuses"
    , "- **Planet Capture**: Successful assault captures planet"
    , "- **Population Loss**: Heavy casualties in ground combat"
    , ""
    , "## Advanced Combat Strategies"
    , ""
    , "### Fleet Composition"
    , "- **Balanced Fleet**: Mix of carriers, battleships, escorts"
    , "- **Specialized Task Forces**: Focused on specific missions"
    , "- **Support Elements**: Fuel ships, repair vessels, scouts"
    , "- **Reserve Forces**: Backup units for reinforcement"
    , ""
    , "### Battle Simulator"
    , "- **Combat Testing**: Simulate battles before committing"
    , "- **Ship Optimization**: Test different weapon loadouts"
    , "- **Tactical Planning**: Predict battle outcomes"
    , "- **Training Tool**: Learn combat mechanics safely"
    , ""
    , "### Combat Intelligence"
    , "- **Enemy Assessment**: Analyze opponent ship designs"
    , "- **Battle Reports**: Study VCRs for tactical lessons"
    , "- **Fleet Tracking**: Monitor enemy fleet movements"
    , "- **Technology Gaps**: Identify advantages and weaknesses"
    , ""
    , "### Engagement Rules"
    , "- **Choose Your Battles**: Fight when you have advantage"
    , "- **Concentration of Force**: Bring overwhelming firepower"
    , "- **Tactical Withdrawal**: Retreat when outmatched"
    , "- **Follow-up Operations**: Exploit victory or recover from defeat"
    , ""
    , "This comprehensive combat guide covers all aspects of warfare"
    , "in VGA Planets!"
    ]