module Guide.Economics where

economicsGuide :: String
economicsGuide = unlines
    [ "# VGA Planets Economics Guide"
    , ""
    , "## Economic Fundamentals"
    , ""
    , "### The Four Pillars of Economy"
    , "1. **Population Management**: Colonists and natives"
    , "2. **Resource Extraction**: Mining operations"
    , "3. **Industrial Production**: Factories and supplies"
    , "4. **Taxation**: Converting population to money"
    , ""
    , "### Economic Victory"
    , "Strong economics enable:"
    , "- Massive fleet construction"
    , "- Rapid technological advancement"
    , "- Sustained military campaigns"
    , "- Recovery from setbacks"
    , ""
    , "## Population Dynamics"
    , ""
    , "### Colonist Growth"
    , "Colonist population grows based on:"
    , "- **Climate**: Temperature affects growth rate"
    , "- **Happiness**: Happy populations grow faster"
    , "- **Capacity**: Planet can support limited population"
    , "- **Government**: Some races have growth bonuses"
    , ""
    , "### Optimal Climates by Race"
    , "- **Federation**: 15-84°F (broad range)"
    , "- **Lizards**: 50-150°F (prefer heat)"
    , "- **Birds**: 0-100°F (adaptable)"
    , "- **Fascists**: 15-85°F (similar to Federation)"
    , "- **Privateers**: 25-85°F (moderate range)"
    , "- **Cyborg**: Any temperature (no climate penalty)"
    , "- **Crystals**: Desert planets (bonus on 81-100°F)"
    , "- **Evil Empire**: 15-80°F"
    , "- **Robots**: Any temperature"
    , "- **Rebels**: 19-80°F"
    , "- **Colonies**: 15-80°F"
    , ""
    , "### Native Populations"
    , "Native types and their benefits:"
    , "- **Humanoids**: 1x taxation, no special bonus"
    , "- **Bovinoids**: 1x taxation, +2 mining rate"
    , "- **Reptilians**: 2x taxation rate"
    , "- **Avians**: 2x taxation rate"
    , "- **Amorphous**: Cannot be taxed, but harmless"
    , "- **Insectoids**: 2x taxation rate from colonists"
    , "- **Amphibians**: 2x taxation rate"
    , "- **Ghipsoldals**: 2x taxation rate"
    , "- **Siliconoids**: 1x taxation, +5 mining rate"
    , ""
    , "## Taxation Mechanics"
    , ""
    , "### Basic Taxation Rules"
    , "- **Separate Taxes**: Colonists and natives taxed independently"
    , "- **Happiness Threshold**: Must maintain > 30 happiness for income"
    , "- **Maximum Revenue**: 5,000 MegaCredits per planet per turn"
    , "- **Base Rate**: 1 MC per colonist clan (2 MC on Insectoid worlds)"
    , ""
    , "### Taxation Strategies"
    , ""
    , "#### 1. Safe Taxation"
    , "- **Goal**: Maintain stable happiness (40-70)"
    , "- **Method**: Tax rate that maintains happiness equilibrium"
    , "- **Pros**: Steady income, no building destruction"
    , "- **Cons**: Lower maximum income potential"
    , ""
    , "#### 2. Growth Taxation"
    , "- **Goal**: Maximize population growth"
    , "- **Method**: Tax to 70 happiness, then 0% tax for recovery"
    , "- **Pros**: Rapid population increase"
    , "- **Cons**: Cyclical income, requires careful timing"
    , ""
    , "#### 3. Strip Mining"
    , "- **Goal**: Maximum immediate revenue"
    , "- **Method**: Tax below 40 happiness to destroy buildings"
    , "- **Pros**: Huge short-term income"
    , "- **Cons**: Permanent economic damage"
    , ""
    , "### Happiness Effects"
    , "- **Above 70**: Population grows rapidly"
    , "- **40-70**: Moderate growth, stable production"
    , "- **31-39**: Slow growth, some income"
    , "- **1-30**: No tax income"
    , "- **Below 0**: Civil war, building destruction"
    , ""
    , "### Building Destruction"
    , "When happiness drops below 40:"
    , "- **Colonists only**: 8 factories + 10 mines lost per turn"
    , "- **Natives only**: 3 factories + 5 mines lost per turn"
    , "- **Both populations**: 11 factories + 15 mines lost per turn"
    , ""
    , "## Mining Operations"
    , ""
    , "### Mineral Types"
    , "- **Tritanium**: Light metal for ship hulls and engines"
    , "- **Duranium**: Heavy metal for ship armor and weapons"
    , "- **Molybdenum**: Rare metal for advanced systems and starbases"
    , ""
    , "### Mining Mechanics"
    , "- **Mines**: Extract minerals based on planet density"
    , "- **Density**: Ranges from 0-100 for each mineral type"
    , "- **Mining Rate**: Mines × Density ÷ 100 = minerals per turn"
    , "- **Native Bonus**: Some natives provide mining bonuses"
    , ""
    , "### Mining Efficiency by Race"
    , "- **Standard Races**: 100% efficiency"
    , "- **Federation**: 70% efficiency (environmental protection)"
    , "- **Lizards**: 200% efficiency (strong workers)"
    , "- **Robots**: 110% efficiency (automated systems)"
    , ""
    , "### Optimal Mining Strategy"
    , "- **High Density Worlds**: Build maximum mines (200+)"
    , "- **Medium Density**: Build moderate mines (100-200)"
    , "- **Low Density**: Minimal mining investment"
    , "- **Native Bonuses**: Prioritize worlds with mining natives"
    , ""
    , "## Factory Production"
    , ""
    , "### Supply Production"
    , "- **Base Rate**: 1 factory produces 1 supply per turn"
    , "- **Colonist Limit**: Can't exceed colonist population"
    , "- **Resource Cost**: Factories require tritanium and duranium"
    , "- **Happiness Cost**: More factories reduce happiness"
    , ""
    , "### Supply Uses"
    , "- **Ship Construction**: Supplies are required for all builds"
    , "- **Starbase Construction**: Large supply requirements"
    , "- **Trading**: Can be converted to money (Privateers)"
    , "- **Planetary Defense**: Some defensive structures need supplies"
    , ""
    , "### Factory Optimization"
    , "- **High Population Worlds**: Build many factories"
    , "- **Climate Matching**: Factories work best with happy populations"
    , "- **Resource Balance**: Don't build more than you can supply"
    , "- **Strategic Location**: Centralize production for efficiency"
    , ""
    , "## Advanced Economic Strategies"
    , ""
    , "### Resource Logistics"
    , "- **Freighter Networks**: Establish regular cargo routes"
    , "- **Central Depots**: Concentrate resources at key starbases"
    , "- **Emergency Reserves**: Maintain stockpiles for crises"
    , "- **Trade Agreements**: Exchange resources with allies"
    , ""
    , "### Economic Specialization"
    , "- **Mining Worlds**: High-density planets with maximum mines"
    , "- **Factory Worlds**: High-population planets with many factories"
    , "- **Tax Worlds**: Optimal climate planets for revenue"
    , "- **Mixed Worlds**: Balanced development for flexibility"
    , ""
    , "### Economic Warfare"
    , "- **Blockade**: Cut enemy supply lines"
    , "- **Raiding**: Attack enemy freighters and mining operations"
    , "- **Pillaging**: Steal enemy resources (Fascist ability)"
    , "- **Economic Espionage**: Gather intelligence on enemy resources"
    , ""
    , "## Economic Development Timeline"
    , ""
    , "### Early Game (Turns 1-20)"
    , "- **Priority**: Explore and colonize planets"
    , "- **Focus**: Basic infrastructure (mines, some factories)"
    , "- **Goals**: Establish resource base and supply lines"
    , "- **Mistakes to Avoid**: Over-taxation, neglecting exploration"
    , ""
    , "### Mid Game (Turns 21-50)"
    , "- **Priority**: Optimize existing planets"
    , "- **Focus**: Maximize mining and factory production"
    , "- **Goals**: Support fleet construction and tech advancement"
    , "- **Expansion**: Continue measured colonization"
    , ""
    , "### Late Game (Turns 51+)"
    , "- **Priority**: Economic warfare and optimization"
    , "- **Focus**: Maximum efficiency and output"
    , "- **Goals**: Support massive military operations"
    , "- **Strategy**: Economic dominance to ensure victory"
    , ""
    , "## Race-Specific Economic Strategies"
    , ""
    , "### Federation"
    , "- **Strength**: Double taxation income"
    , "- **Weakness**: Reduced mining efficiency"
    , "- **Strategy**: Focus on high-population tax worlds"
    , ""
    , "### Lizards"
    , "- **Strength**: Double mining speed"
    , "- **Tactic**: Aggressive early expansion for resource control"
    , "- **Strategy**: Hiss mission for economic bonuses"
    , ""
    , "### Privateers"
    , "- **Ability**: Convert supplies to money via gambling"
    , "- **Strategy**: Rob enemy ships for additional income"
    , "- **Tactic**: Economic warfare through theft"
    , ""
    , "### Cyborg"
    , "- **Limitation**: Maximum 20% native taxation"
    , "- **Compensation**: Assimilate enemy economic assets"
    , "- **Strategy**: Technology focus with chunnel logistics"
    , ""
    , "This comprehensive economics guide provides the foundation for"
    , "building a dominant economic empire in VGA Planets!"
    ]
