module Guide.FriendlyCodes where

friendlyCodesGuide :: String
friendlyCodesGuide = unlines
    [ "# VGA Planets Friendly Codes Complete Guide"
    , ""
    , "## Friendly Code Fundamentals"
    , ""
    , "### What are Friendly Codes?"
    , "Friendly codes are three-character strings that:"
    , "- **Control Behavior**: Modify ship and planet actions"
    , "- **Enable Abilities**: Activate special racial powers"
    , "- **Prevent Combat**: Ships with matching codes don't fight"
    , "- **Coordinate Actions**: Synchronize complex operations"
    , ""
    , "### Code Properties"
    , "- **Case Insensitive**: 'ABC' = 'abc' = 'AbC'"
    , "- **Three Characters**: Exactly 3 letters, numbers, or symbols"
    , "- **Universal**: Set on both ships and planets"
    , "- **Turn-Based**: Codes take effect when turn is submitted"
    , ""
    , "## Essential Ship Codes"
    , ""
    , "### Basic Ship Operations"
    , "- **HYP**: Hyperspace jump (if ship has hyperdrive)"
    , "- **NTP**: No Torpedoes - prevent launching torpedoes/fighters"
    , "- **NUK**: Nuclear missiles - use nuclear torpedoes if available"
    , "- **ATT**: Attack - engage enemy ships/planets regardless of codes"
    , ""
    , "### Ship Transfer Codes"
    , "- **GSx**: Give Ship to player X (where x = 1-9, A-B for players 10-11)"
    , "- **Examples**: GS1 (give to player 1), GSA (give to player 10)"
    , "- **Requirements**: Both players must agree to transfer"
    , "- **Instant**: Transfer occurs immediately"
    , ""
    , "### Special Mission Codes"
    , "- **POP**: Fascist Glory Device - detonate ship for massive damage"
    , "- **TRN**: Transport - beam down colonists automatically"
    , "- **COL**: Colonize - establish colony if planet uninhabited"
    , "- **SUR**: Surrender - give up ship to enemy (rare use)"
    , ""
    , "## Essential Planet Codes"
    , ""
    , "### Planetary Defense"
    , "- **ATT**: Attack - defense posts engage enemy ships"
    , "- **NUK**: Nuclear defense - maximum defensive fire"
    , "- **BUM**: Beam Up MegaCredits - transfer money to friendly ships"
    , "- **BUD**: Beam Up Duranium - transfer duranium to ships"
    , "- **BUT**: Beam Up Tritanium - transfer tritanium to ships"
    , "- **BUM**: Beam Up Molybdenum - transfer molybdenum to ships"
    , ""
    , "### Resource Management"
    , "- **BUS**: Beam Up Supplies - transfer supplies to ships"
    , "- **BUC**: Beam Up Colonists - transfer population to ships"
    , "- **BUF**: Beam Up Fuel - transfer fuel to ships (if available)"
    , ""
    , "## Race-Specific Codes"
    , ""
    , "### Solar Federation"
    , "- **All Standard Codes**: No unique friendly codes"
    , "- **Super Refit**: Can refit ships regardless of starbase tech"
    , ""
    , "### Lizard Alliance"
    , "- **HIS**: Hiss mission - improve planet happiness and economy"
    , "- **Standard Codes**: All universal codes available"
    , ""
    , "### Empire of Birds"
    , "- **SPY**: Super Spy mission - gather intelligence, change enemy codes"
    , "- **SEN**: Sensor Sweep - detect cloaked ships"
    , "- **CLO**: Cloak ship (for cloaking-capable vessels)"
    , ""
    , "### Fascist Empire"
    , "- **POP**: Glory Device - self-destruct for area damage"
    , "- **PIL**: Pillage mission - steal supplies from planets"
    , "- **ATT**: Enhanced attack capabilities"
    , ""
    , "### Privateer Bands"
    , "- **ROB**: Rob mission - steal money from enemy ships"
    , "- **GAM**: Gambling - convert supplies to money"
    , "- **CAP**: Capture mission - board and take enemy ships"
    , ""
    , "### Cyborg"
    , "- **CHU**: Chunnel - instant transport between Firecloud ships"
    , "- **ASS**: Assimilate - convert enemy ships/planets"
    , "- **REP**: Self-repair enhanced mode"
    , ""
    , "### Crystal Confederation"
    , "- **WEB**: Web mine laying - create web minefields"
    , "- **LAY**: Standard mine laying enhanced for crystals"
    , "- **DES**: Desert advantage activation"
    , ""
    , "### Evil Empire"
    , "- **DRK**: Dark Sense - detect cloaked enemies"
    , "- **IMP**: Imperial Assault - enhanced ground combat"
    , "- **RAY**: Death Ray - destroy planet population"
    , ""
    , "### Robotic Imperium"
    , "- **REP**: Enhanced self-repair mode"
    , "- **BLD**: Enhanced building/production"
    , "- **MIN**: Enhanced mining operations"
    , ""
    , "### Rebel Confederation"
    , "- **REB**: Rebel Ground Combat bonus"
    , "- **GUE**: Guerrilla warfare mode"
    , "- **DEF**: Enhanced planetary defense"
    , ""
    , "### Missing Colonies of Man"
    , "- **CLO**: Cloak capable ships"
    , "- **SAL**: Salvage mission - recover battle debris"
    , "- **COL**: Enhanced colonization abilities"
    , ""
    , "## Advanced Code Usage"
    , ""
    , "### Mine Laying Codes"
    , "- **MDX**: Add mines to minefield X (where X = 1-9)"
    , "- **MIX**: Scoop mines from minefield X"
    , "- **Examples**: MD5 (add to field 5), MI3 (scoop from field 3)"
    , "- **Strategy**: Control specific minefield ownership"
    , ""
    , "### Combat Coordination"
    , "- **Matching Codes**: Ships with same codes don't fight each other"
    , "- **Alliance Codes**: Coordinate with allied players"
    , "- **Attack Override**: ATT code forces combat regardless"
    , "- **Defensive Codes**: Protect valuable ships from accidental combat"
    , ""
    , "### Resource Coordination"
    , "- **Transfer Codes**: Coordinate resource movement"
    , "- **Supply Chains**: Code ships for efficient logistics"
    , "- **Emergency Codes**: Rapid resource deployment"
    , "- **Security Codes**: Prevent unauthorized access"
    , ""
    , "## Strategic Code Applications"
    , ""
    , "### Fleet Operations"
    , "- **Formation Codes**: Keep fleets coordinated"
    , "- **Mission Codes**: Assign specific roles to ships"
    , "- **Recognition Codes**: Identify friendly vs enemy"
    , "- **Tactical Codes**: Coordinate complex maneuvers"
    , ""
    , "### Diplomatic Codes"
    , "- **Alliance Codes**: Shared codes with allies"
    , "- **Neutral Codes**: Avoid conflict with non-enemies"
    , "- **Trade Codes**: Facilitate resource exchange"
    , "- **Ceasefire Codes**: Temporary peace agreements"
    , ""
    , "### Economic Codes"
    , "- **Trade Route Codes**: Coordinate cargo movements"
    , "- **Production Codes**: Manage industrial operations"
    , "- **Tax Codes**: Optimize revenue collection"
    , "- **Development Codes**: Coordinate planet development"
    , ""
    , "## Code Security and Intelligence"
    , ""
    , "### Code Security"
    , "- **Regular Changes**: Update codes to prevent enemy exploitation"
    , "- **Compartmentalization**: Different codes for different operations"
    , "- **Deception**: Use misleading codes to confuse enemies"
    , "- **Communication Security**: Coordinate code changes with allies"
    , ""
    , "### Intelligence Gathering"
    , "- **Code Breaking**: Observe enemy patterns to deduce codes"
    , "- **Super Spy**: Birds can steal and change enemy codes"
    , "- **Pattern Analysis**: Look for systematic code usage"
    , "- **Counterintelligence**: Protect your own code systems"
    , ""
    , "### Enemy Code Exploitation"
    , "- **Captured Codes**: Use codes from captured ships/planets"
    , "- **Code Mimicry**: Copy enemy codes to avoid detection"
    , "- **False Flag**: Use enemy codes for deception"
    , "- **Code Jamming**: Force enemies to change codes frequently"
    , ""
    , "## Common Code Mistakes"
    , ""
    , "### Accidental Combat"
    , "- **Mismatched Codes**: Friendly ships attacking each other"
    , "- **Code Typos**: Wrong codes causing unintended actions"
    , "- **Forgotten Updates**: Old codes causing problems"
    , "- **Alliance Confusion**: Wrong codes with allied players"
    , ""
    , "### Security Breaches"
    , "- **Predictable Codes**: Using obvious or sequential codes"
    , "- **Unchanged Codes**: Keeping same codes too long"
    , "- **Shared Codes**: Using same codes across multiple operations"
    , "- **Captured Intelligence**: Codes revealed through enemy capture"
    , ""
    , "### Operational Failures"
    , "- **Wrong Mission Codes**: Ships doing wrong missions"
    , "- **Resource Waste**: Incorrect transfer codes"
    , "- **Tactical Confusion**: Poor coordination due to bad codes"
    , "- **Communication Breakdown**: Misunderstood code meanings"
    , ""
    , "This comprehensive friendly codes guide covers all aspects of"
    , "code usage and strategy in VGA Planets!"
    ]