module Guide.FullGuide where

fullGameGuideContent :: String
fullGameGuideContent = unlines
    [ "# Planets.nu Complete Gameplay Guide"
    , ""
    , "## Table of Contents"
    , "1. Game Overview"
    , "2. The 12 Races and Their Abilities"
    , "3. Ship Missions"
    , "4. Combat System"
    , "5. Planetary Management"
    , "6. Starships and Starbases"
    , "7. Economic System"
    , "8. Navigation and Movement"
    , "9. Game Mechanics"
    , "10. Victory Conditions"
    , "11. Strategic Guides"
    , ""
    , "## 1. Game Overview"
    , "Planets.nu is a multiplayer turn-based space strategy game based on VGA Planets."
    , "Players control one of 12 unique races, each with special abilities."
    , "The goal is to achieve victory through military conquest, economic dominance, or meeting specific win conditions."
    , ""
    , "## 2. The 12 Races and Their Abilities"
    , ""
    , "### Solar Federation (Race 1)"
    , "**Special Abilities:**"
    , "- 200% Taxing: Can tax at double the normal rate"
    , "- Super Refit: Can upgrade ships to new hulls"
    , "- Fed Crew Bonus: Enhanced ship performance"
    , "**Disadvantages:**"
    , "- 70% Mining Efficiency: Reduced mineral extraction"
    , "**Strategy:** Diplomatic and economic powerhouse with strong late-game potential"
    , ""
    , "### Lizard Alliance (Race 2)"
    , "**Special Abilities:**"
    , "- 200% Mining: Double mining efficiency"
    , "- 30:1 Ground Combat Attack, 15:1 Defense: Strongest ground forces"
    , "- Hiss Mission: Improves planet happiness and economy"
    , "- Lizard Crew Bonus: Ships take 150% damage but ignore first 50% engine/weapon damage"
    , "**Strategy:** Early aggressive expansion through superior ground combat"
    , ""
    , "### Empire of the Birds (Race 3)"
    , "**Special Abilities:**"
    , "- Cloaking: Large fleet of cloaking ships"
    , "- Super Spy Mission: Reveals enemy defenses and can change friendly codes"
    , "- Advanced Cloak: Improved cloaking technology"
    , "**Key Ships:** Dark Wing Class Battleship (only cloaking battleship)"
    , "**Strategy:** Stealth warfare and intelligence gathering"
    , ""
    , "### Hordes of Fury (Race 4)"
    , "**Special Abilities:**"
    , "- Pillage Mission: Steal supplies from enemy planets"
    , "- Glory Device: Ships can self-destruct for massive area damage"
    , "- 2X Beam Charge Rate: Faster beam weapon recharge"
    , "**Strategy:** Aggressive raiding and scorched earth tactics"
    , ""
    , "### Privateer Bands (Race 5)"
    , "**Special Abilities:**"
    , "- Rob Mission: Steal money from enemy ships"
    , "- Boarding: Capture enemy ships in combat"
    , "- Gambling: Convert supplies to megacredits"
    , "**Strategy:** Economic warfare through theft and piracy"
    , ""
    , "### Cyborg (Race 6)"
    , "**Special Abilities:**"
    , "- Assimilation: Convert enemy ships and planets"
    , "- Self Repair: Ships automatically repair damage"
    , "- Warp Chunnel: Instant transport between starbases"
    , "**Disadvantages:**"
    , "- 20% Native Tax Limit: Reduced native taxation"
    , "**Strategy:** Technology-focused with assimilation expansion"
    , ""
    , "### Crystal Confederation (Race 7)"
    , "**Special Abilities:**"
    , "- Web Mines: Create area denial minefields that drain fuel"
    , "- Desert Advantage: Thrive on desert planets"
    , "- Lay Web Mines Mission: Deploy web minefields"
    , "**Key Ships:** Crystal Thunder Class Battleship"
    , "**Strategy:** Defensive minefield control and area denial"
    , ""
    , "### Evil Empire (Race 8)"
    , "**Special Abilities:**"
    , "- Dark Sense: Detect cloaked ships within 100 LY"
    , "- Imperial Assault: Enhanced ground combat capabilities"
    , "- Fighter Bonus: Improved fighter performance"
    , "**Strategy:** Anti-cloaking specialists and fighter combat"
    , ""
    , "### Robotic Imperium (Race 9)"
    , "**Special Abilities:**"
    , "- Self Repair: Ships automatically repair damage"
    , "- 4X Mining: Quadruple mining efficiency"
    , "- Lay Mines Mission: Deploy regular minefields"
    , "**Strategy:** Industrial powerhouse with strong mining economy"
    , ""
    , "### Rebel Confederation (Race 10)"
    , "**Special Abilities:**"
    , "- Rebel Ground Attack: Special ground combat mission"
    , "- Planet Immunity: Immune to some planet-based attacks"
    , "- Fighter Bonus: Enhanced fighter capabilities"
    , "**Strategy:** Versatile fighters with defensive advantages"
    , ""
    , "### Missing Colonies of Man (Race 11)"
    , "**Special Abilities:**"
    , "- Cloaking: Access to cloaking ships"
    , "- Fighter Bonus: Enhanced fighter performance"
    , "- Privateer Bonus: Some privateering abilities"
    , "**Strategy:** Balanced approach with stealth options"
    , ""
    , "### Horwasp Plague (Race 12)"
    , "**Special Abilities:**"
    , "- Swarm: Special mass attack capability"
    , "- Insect Advantages: Unique biological traits"
    , "- Hive Mind: Collective intelligence bonuses"
    , "**Strategy:** Overwhelming numbers and biological warfare"
    , ""
    , "## 3. Ship Missions"
    , ""
    , "### Standard Missions (Available to All Ships)"
    , "1. **Exploration** - Default mission for movement and exploration"
    , "2. **Mine Sweep** - Clear minefields from space"
    , "3. **Lay Mines** - Deploy minefields (requires torpedo tubes)"
    , "4. **Kill!** - Attack all enemy ships at location"
    , "5. **Sensor Sweep** - Scan for enemy ships and planets"
    , "6. **Land and Disassemble** - Colonize planets or scrap ship"
    , "7. **Try to Tow** - Attempt to tow another ship"
    , "8. **Intercept** - Pursue and attack enemy ships"
    , "9. **Enter Wormhole** - Travel through wormholes"
    , "10. **Load Artifact** - Collect special artifacts"
    , "11. **Transfer Artifact** - Move artifacts between ships"
    , "12. **Beam Up** - Collect cargo from space"
    , ""
    , "### Special Missions (Race/Ship Specific)"
    , "- **Bioscan** - Scan planet for biological information"
    , "- **Build Clans** - Increase population on planets"
    , "- **Build Fighters** - Construct fighter squadrons"
    , "- **Cloak** - Become invisible to enemy sensors"
    , "- **Cloak and Intercept** - Combine cloaking with pursuit"
    , "- **Dark Sense** - Detect cloaked ships (Evil Empire)"
    , "- **Destroy Planet** - Annihilate entire planets"
    , "- **Hisssss!** - Improve planet happiness (Lizards)"
    , "- **Lay Web Mines** - Deploy web minefields (Crystals)"
    , "- **Pillage Planet** - Steal resources from planets (Fury)"
    , "- **Plunder Planet** - Advanced resource theft"
    , "- **Rebel Ground Attack** - Special ground assault (Rebels)"
    , "- **Repair Self** - Automatically repair ship damage"
    , "- **Repair Ship** - Fix other ships in fleet"
    , "- **Rob Ship** - Steal money from enemy ships (Privateers)"
    , "- **Super Refit** - Upgrade ship hulls (Federation)"
    , "- **Super Spy** - Advanced intelligence gathering (Birds)"
    , "- **Swarm** - Mass attack coordination (Horwasp)"
    , "- **Warp Chunnel** - Instant transport (Cyborg)"
    , ""
    , "## 4. Combat System"
    , ""
    , "### Combat Triggers"
    , "Combat occurs when:"
    , "- Two unfriendly objects occupy the same space"
    , "- A ship has the Kill! mission"
    , "- Primary Enemy is set"
    , "- Planet's Friendly Code is NUK or ATT"
    , ""
    , "### Combat Phases"
    , "1. **Fighter Phase** - Longest range, attack first"
    , "2. **Torpedo Phase** - Medium range, high damage"
    , "3. **Beam Phase** - Short range, drawn from engines"
    , ""
    , "### Weapon Types"
    , "**Torpedoes:**"
    , "- Mark 1-8: Increasing damage and mine capability"
    , "- Most powerful weapon system"
    , "- Limited ammunition"
    , ""
    , "**Beam Weapons:**"
    , "- Laser to Heavy Phaser (Tech 1-10)"
    , "- Unlimited ammunition but draws engine power"
    , "- Good against fighters and lightly armored ships"
    , ""
    , "**Fighters:**"
    , "- Longest combat range"
    , "- Effective against large ships"
    , "- Vulnerable to beam weapons"
    , ""
    , "### Ground Combat"
    , "Ground combat uses assault/defense ratios:"
    , "- Standard races: 1:1 attack, 1:1 defense"
    , "- Lizards: 30:1 attack, 15:1 defense"
    , "- Other races have various bonuses"
    , ""
    , "## 5. Planetary Management"
    , ""
    , "### Climate System"
    , "Planets have temperatures from 0-100 degrees:"
    , "- Each race has optimal temperature ranges"
    , "- Temperature affects colonist growth"
    , "- Terraform missions can alter climate"
    , ""
    , "### Population and Happiness"
    , "- Colonist happiness affects tax income"
    , "- Below 31 happiness: No tax income"
    , "- Below 0 happiness: Civil war begins"
    , "- Happiness affected by taxes, overpopulation, and structures"
    , ""
    , "### Native Races"
    , "- **Humanoids** - Standard taxation"
    , "- **Bovinoids** - Mining bonus"
    , "- **Reptilians** - Taxation bonus"
    , "- **Avians** - Taxation bonus"
    , "- **Amorphous** - Cannot be taxed"
    , "- **Insectoids** - Double taxation rate"
    , "- **Amphibians** - Taxation bonus"
    , "- **Ghipsoldals** - Taxation bonus"
    , "- **Siliconoids** - Mining bonus"
    , ""
    , "### Taxation System"
    , "- Tax rates from 0-100%"
    , "- Maximum 5,000 MC per planet per turn"
    , "- Insectoids provide 2 MC per clan"
    , "- Other natives provide 1 MC per clan"
    , ""
    , "### Structures"
    , "- **Mines** - Extract minerals from planet"
    , "- **Factories** - Produce supplies"
    , "- **Defense Posts** - Protect against ground attack"
    , "- More structures = lower happiness"
    , ""
    , "## 6. Starships and Starbases"
    , ""
    , "### Ship Categories"
    , "**Freighters:**"
    , "- Large cargo capacity"
    , "- Minimal weapons"
    , "- Economic and transport roles"
    , ""
    , "**Warships:**"
    , "- Heavy weapons and armor"
    , "- Fighter bays and torpedo tubes"
    , "- Combat-focused design"
    , ""
    , "### Engine Technology"
    , "9 engine types with different warp efficiencies:"
    , "- StarDrive 1: Efficient at Warp 1"
    , "- Transwarp Drive: Efficient at Warp 9"
    , "- Higher tech = better fuel efficiency at high warp"
    , ""
    , "### Starbase Functions"
    , "- **Ship Construction** - Build new ships"
    , "- **Tech Research** - Advance technology levels"
    , "- **Ship Repair** - Fix damaged vessels"
    , "- **Defense** - Protect planets with fighters and weapons"
    , ""
    , "### Tech Levels"
    , "- **Hull Tech** - Available ship designs"
    , "- **Engine Tech** - Engine types and efficiency"
    , "- **Beam Tech** - Weapon systems"
    , "- **Torpedo Tech** - Torpedo types and damage"
    , ""
    , "## 7. Economic System"
    , ""
    , "### Resources"
    , "- **Megacredits** - Primary currency from taxation"
    , "- **Supplies** - Produced by factories, used for construction"
    , "- **Neutronium** - Fuel for starships"
    , "- **Tritanium** - Hull construction material"
    , "- **Duranium** - Engine and weapon construction"
    , "- **Molybdenum** - Advanced technology components"
    , ""
    , "### Trade and Economy"
    , "- Transfer resources between ships and planets"
    , "- Trade agreements with other players"
    , "- Resource scarcity drives strategic decisions"
    , ""
    , "## 8. Navigation and Movement"
    , ""
    , "### Movement System"
    , "- Ships move in straight lines between waypoints"
    , "- Fuel consumption based on warp speed and distance"
    , "- Higher warp = exponentially more fuel"
    , ""
    , "### Space Phenomena"
    , "- **Ion Storms** - Damage ships and disrupt movement"
    , "- **Wormholes** - Instant transport across the galaxy"
    , "- **Warp Wells** - Gravitational anomalies affecting movement"
    , "- **Nebulae** - Reduce sensor range and visibility"
    , ""
    , "### Friendly Codes"
    , "3-character codes that control ship and planet behavior:"
    , "- **NUK** - Planet attacks all ships"
    , "- **ATT** - Planet attacks enemy ships"
    , "- **mkt** - Sell supplies at starbase"
    , "- Many race-specific codes with special effects"
    , ""
    , "## 9. Game Mechanics"
    , ""
    , "### Host Order"
    , "86-step process that determines turn resolution:"
    , "1. Movement and fuel consumption"
    , "2. Combat resolution"
    , "3. Production and construction"
    , "4. Population growth and happiness changes"
    , "5. Victory condition checks"
    , ""
    , "### Turn Structure"
    , "- Players submit orders simultaneously"
    , "- Host processes all orders"
    , "- Results sent to all players"
    , "- Typical turn frequency: 1-3 times per week"
    , ""
    , "### Communication"
    , "- In-game messaging system"
    , "- Diplomacy and alliance formation"
    , "- Trade negotiations and agreements"
    , ""
    , "## 10. Victory Conditions"
    , ""
    , "### Standard Victory Conditions"
    , "1. **Military Victory** - Destroy all enemy races"
    , "2. **Economic Victory** - Control majority of planets and resources"
    , "3. **Territorial Victory** - Control specified percentage of galaxy"
    , "4. **Alliance Victory** - Coordinate with allies to meet group goals"
    , "5. **Artifact Victory** - Collect and control special artifacts"
    , "6. **Construction Victory** - Build specific megastructures"
    , "7. **Research Victory** - Achieve technological supremacy"
    , ""
    , "### Campaign-Specific Victory"
    , "Some games have unique victory conditions:"
    , "- Scenario-based objectives"
    , "- Time-limited goals"
    , "- Special artifact requirements"
    , ""
    , "## 11. Strategic Guides"
    , ""
    , "### Early Game Strategy (Turns 1-30)"
    , "1. **Explore** - Map surrounding space and locate planets"
    , "2. **Colonize** - Establish new colonies on suitable planets"
    , "3. **Build Economy** - Construct mines and factories"
    , "4. **Scout** - Locate other players and assess threats"
    , "5. **Diplomacy** - Establish early contact and alliances"
    , ""
    , "### Mid Game Strategy (Turns 30-60)"
    , "1. **Tech Advancement** - Research higher technology levels"
    , "2. **Fleet Building** - Construct warships and defenses"
    , "3. **Territory Control** - Secure strategic regions"
    , "4. **Alliance Management** - Maintain beneficial relationships"
    , "5. **Resource Stockpiling** - Prepare for major conflicts"
    , ""
    , "### Late Game Strategy (Turns 60+)"
    , "1. **Major Warfare** - Large-scale fleet battles"
    , "2. **Victory Push** - Focus on winning conditions"
    , "3. **Alliance Warfare** - Coordinate with allies"
    , "4. **Economic Dominance** - Control key resources"
    , "5. **Endgame Diplomacy** - Final negotiations and betrayals"
    , ""
    , "### Race-Specific Strategies"
    , ""
    , "**Federation:** Focus on economic growth and late-game technology"
    , "**Lizards:** Early aggressive expansion with ground combat"
    , "**Birds:** Stealth warfare and intelligence operations"
    , "**Fury:** Aggressive raiding and resource denial"
    , "**Privateers:** Economic warfare and ship capture"
    , "**Cyborg:** Technological advancement and assimilation"
    , "**Crystals:** Defensive positioning with web mine control"
    , "**Empire:** Anti-stealth operations and fighter combat"
    , "**Robots:** Industrial powerhouse with mining focus"
    , "**Rebels:** Flexible tactics with defensive advantages"
    , "**Colonies:** Balanced approach with multiple options"
    , "**Horwasp:** Overwhelming numbers and biological warfare"
    , ""
    , "## Advanced Tactics"
    , ""
    , "### Fleet Composition"
    , "- Balance between different ship types"
    , "- Carrier groups with fighter support"
    , "- Escort vessels for protection"
    , "- Specialized ships for specific missions"
    , ""
    , "### Combat Tactics"
    , "- Ship positioning and formation"
    , "- Weapon selection and targeting"
    , "- Retreat and regrouping strategies"
    , "- Coordinated attacks with allies"
    , ""
    , "### Economic Warfare"
    , "- Resource denial and blockades"
    , "- Trade route disruption"
    , "- Industrial target prioritization"
    , "- Economic intelligence gathering"
    , ""
    , "### Diplomatic Strategies"
    , "- Alliance formation and management"
    , "- Treaty negotiation and enforcement"
    , "- Information sharing and intelligence"
    , "- Betrayal timing and execution"
    , ""
    , "---"
    , ""
    , "This comprehensive guide covers all major aspects of Planets.nu gameplay."
    , "Master these concepts to dominate the galaxy and achieve victory!"
    , ""
    , "For specific tactical advice, consult the individual race guides and"
    , "specialized strategy documents available in the game's help system."
    ]
