module Guide.Homeworlds where

homeworldsGuide :: String
homeworldsGuide = unlines
    [ "# VGA Planets Homeworld Location Guide"
    , ""
    , "## Understanding Homeworld Placement"
    , ""
    , "### Game Setup Fundamentals"
    , "In VGA Planets, homeworlds are distributed using specific algorithms:"
    , "- **Distribution Patterns**: Circular, Random Spaced, Left/Right, or One vs Circle"
    , "- **Minimum Distance Rule**: HomeworldsRadius parameter (typically 100+ ly)"
    , "- **Planet Proximity**: Min 155 ly from other planets to homeworld"
    , "- **Neighbor Planets**: 12+ planets within 81-162 ly of each homeworld"
    , "- **Host Configuration**: Distance ranges from 150-900 ly (medium) to 400-2800 ly (very long)"
    , ""
    , "### Typical Homeworld Characteristics"
    , "All homeworlds share certain features:"
    , "- **Perfect Climate**: Temperature exactly suited to the race"
    , "- **High Minerals**: Usually 50+ density in multiple minerals"
    , "- **Large Size**: Typically 100+ diameter"
    , "- **No Natives**: Homeworlds never have native populations"
    , "- **Starting Infrastructure**: Pre-built mines, factories, and starbase"
    , ""
    , "## Host Placement Algorithms"
    , ""
    , "### Standard Distribution Patterns"
    , "The host uses these geometric placement algorithms:"
    , "- **Circular (Default)**: Homeworlds arranged in a circle around map center"
    , "- **Random Spaced**: Random placement with minimum distance constraints"
    , "- **Left and Right**: Two-sided placement (works best on square maps)"
    , "- **One vs Circle**: One player in center, others in circle (team games)"
    , ""
    , "### Distance Validation Rules"
    , "The host enforces these constraints during placement:"
    , "- **HomeworldsRadius**: Minimum distance between any two homeworlds"
    , "- **Planet Exclusion Zone**: 155 ly minimum from homeworld to other planets"
    , "- **Neighbor Planet Count**: Ensures 12+ planets within 81-162 ly range"
    , "- **Map Edge Avoidance**: Prevents homeworlds too close to map boundaries"
    , ""
    , "### Exponential Distance Probability"
    , "Planet placement around homeworlds follows:"
    , "- **Probability Formula**: exp(-Distance/BaseFactor)"
    , "- **81 LY Rule**: Guaranteed planets within 81 ly of homeworld"
    , "- **162 LY Zone**: Strategic planet density zone"
    , "- **Beyond 162 LY**: Exponentially decreasing planet probability"
    , ""
    , "## Distance Analysis Methods"
    , ""
    , "### First Contact Distance Estimation"
    , "When you first encounter another player's ships:"
    , "- **Turn of Contact**: Earlier contact = closer homeworld"
    , "- **Ship Type**: Scouts suggest closer base, warships suggest farther"
    , "- **Fuel Levels**: Low fuel suggests ship is near maximum range"
    , "- **Ship Age**: Check ship ID numbers for construction timing"
    , ""
    , "### Host Distance Configuration"
    , "Hosts configure homeworld separation using these ranges:"
    , "- **Short Range**: 5-200 ly between homeworlds"
    , "- **Medium Range**: 150-900 ly (default setting)"
    , "- **Long Range**: 200-1200 ly (recommended for 11-player games)"
    , "- **Very Long Range**: 400-2800 ly separation"
    , "- **Practical Average**: Most games use 200-400 ly spacing"
    , ""
    , "## Exploration Pattern Analysis"
    , ""
    , "### Ship Movement Patterns"
    , "Analyze enemy ship movements to deduce homeworld location:"
    , "- **Radial Exploration**: Ships spreading outward from a center point"
    , "- **Supply Lines**: Freighters moving in consistent directions"
    , "- **Return Trips**: Ships periodically returning to same area"
    , "- **Fuel Discipline**: Ships maintaining enough fuel to return home"
    , ""
    , "### Colonial Expansion Indicators"
    , "Look for colonization patterns:"
    , "- **Nearest First**: Players typically colonize closest good planets"
    , "- **Defensive Positions**: Colonies placed to protect homeworld"
    , "- **Resource Focus**: Colonies chosen for specific mineral needs"
    , "- **Transport Routes**: Regular cargo ship movements"
    , ""
    , "## Intelligence Gathering Techniques"
    , ""
    , "### Direct Observation"
    , "- **Ship Scanning**: Use sensors to identify ship origins"
    , "- **Planet Scanning**: Look for heavily developed worlds"
    , "- **Starbase Detection**: Find tech-advanced starbases"
    , "- **Fleet Concentrations**: Large ship gatherings near homeworlds"
    , ""
    , "### Indirect Intelligence"
    , "- **Economic Activity**: High supply/mineral production areas"
    , "- **Tech Advancement**: Areas with advanced ship designs"
    , "- **Defensive Measures**: Minefields protecting key areas"
    , "- **Population Centers**: High colonist populations"
    , ""
    , "## Mathematical Estimation Methods"
    , ""
    , "### Triangulation Technique"
    , "When you know multiple enemy ship positions:"
    , "1. **Plot Known Contacts**: Mark where you've seen enemy ships"
    , "2. **Estimate Maximum Range**: Consider fuel capacity and turn count"
    , "3. **Draw Range Circles**: Create circles of possible homeworld distance"
    , "4. **Find Intersection**: Homeworld likely where circles overlap"
    , ""
    , "### Fuel-Based Calculations"
    , "Estimate maximum travel distance using host rules:"
    , "- **Ship Fuel Capacity**: Check enemy ship designs if known"
    , "- **Fuel Consumption**: Warp 6 uses ~36 kt fuel per 100 ly"
    , "- **Reserve Fuel**: Players typically keep 25-50% fuel reserve"
    , "- **Round Trip Range**: Halve maximum range for exploration ships"
    , "- **Host Distance Limits**: Use known host configuration to bound estimates"
    , ""
    , "### Time-Based Analysis"
    , "Track enemy expansion over multiple turns:"
    , "- **Expansion Rate**: How fast are they spreading?"
    , "- **Direction Changes**: When do they shift exploration focus?"
    , "- **Consolidation**: When do they stop expanding and develop?"
    , "- **First Contact Turn**: Backtrack from when you first met"
    , ""
    , "## Race-Specific Indicators"
    , ""
    , "### High-Mobility Races"
    , "Races with movement advantages:"
    , "- **Privateers**: Gravitonic ships have extended range"
    , "- **Robots**: Self-repairing ships can travel farther"
    , "- **Birds**: Cloaked ships may appear from unexpected directions"
    , ""
    , "### Economic Powerhouses"
    , "Races with strong economies:"
    , "- **Federation**: Double taxation creates rich homeworlds"
    , "- **Fascist**: Pillaging may indicate homeworld resource needs"
    , "- **Lizards**: Ground assault suggests territorial expansion"
    , ""
    , "### Defensive Specialists"
    , "Races that fortify heavily:"
    , "- **Crystals**: Web minefields around important areas"
    , "- **Empire**: Glory device ships stationed defensively"
    , "- **Cyborg**: Firecloud chunnel networks from homeworld"
    , ""
    , "## Practical Search Strategies"
    , ""
    , "### Using Host Configuration Knowledge"
    , "If you know the host settings:"
    , "1. **Check Game Info**: Look for distance range configuration"
    , "2. **Apply Constraints**: Use min/max distance to bound search area"
    , "3. **Pattern Recognition**: Identify if Circular or Random Spaced was used"
    , "4. **Planet Density**: Look for 81-162 ly planet clusters"
    , ""
    , "### Systematic Grid Search"
    , "When you have a general area:"
    , "1. **Define Search Zone**: Based on host rules and triangulation"
    , "2. **Grid Pattern**: Divide area into search squares"
    , "3. **Fast Scouts**: Use high-warp ships for efficiency"
    , "4. **Sensor Sweep**: Look for developed planets and starbases"
    , ""
    , "### Following the Trail"
    , "Track enemy movements:"
    , "1. **Shadow Ships**: Follow enemy vessels discretely"
    , "2. **Note Destinations**: Where do they go when not exploring?"
    , "3. **Supply Runs**: Freighters often return to homeworld"
    , "4. **Refueling Stops**: Ships may stop at forward bases"
    , ""
    , "### Economic Intelligence"
    , "Look for economic indicators:"
    , "- **Megacredit Spending**: Large purchases suggest rich planets"
    , "- **Ship Production**: Multiple new ships suggest starbase activity"
    , "- **Tech Advancement**: Rapid tech growth indicates homeworld"
    , "- **Mineral Trade**: Large mineral movements"
    , ""
    , "## Defensive Considerations"
    , ""
    , "### Homeworld Security"
    , "Most players protect homeworlds with:"
    , "- **Standing Fleet**: Combat ships stationed at homeworld"
    , "- **Minefield Networks**: Defensive minefields in approaches"
    , "- **Early Warning**: Scout ships on patrol routes"
    , "- **Starbase Defenses**: Maximum tech and fighter complement"
    , ""
    , "### Approach Planning"
    , "When attacking a suspected homeworld:"
    , "- **Multiple Routes**: Approach from unexpected directions"
    , "- **Fuel Planning**: Ensure enough fuel for combat and retreat"
    , "- **Intelligence First**: Scout defenses before committing fleet"
    , "- **Timing**: Coordinate with diplomatic or military distractions"
    , ""
    , "## Common Estimation Errors"
    , ""
    , "### Overestimating Distance"
    , "- **Forward Bases**: Enemy may have established advanced colonies"
    , "- **Fuel Efficiency**: Some races have better fuel economy"
    , "- **Chunnel Networks**: Cyborg tunneling extends effective range"
    , "- **Towing**: Ships may be towed beyond normal range"
    , ""
    , "### Underestimating Distance"
    , "- **Conservative Expansion**: Some players explore slowly"
    , "- **Defensive Focus**: Heavy homeworld investment over expansion"
    , "- **Resource Constraints**: Fuel shortages limiting exploration"
    , "- **Diplomatic Restrictions**: Agreements limiting expansion"
    , ""
    , "## Advanced Techniques"
    , ""
    , "### Pattern Recognition"
    , "Identify player tendencies:"
    , "- **Expansion Style**: Aggressive vs. conservative growth"
    , "- **Defensive Priorities**: What they protect first"
    , "- **Economic Focus**: Mining vs. manufacturing emphasis"
    , "- **Ship Design Preferences**: Combat vs. utility focus"
    , ""
    , "### Multi-Source Correlation"
    , "Combine different intelligence types:"
    , "- **Ship Sightings**: Direct observation data"
    , "- **Economic Analysis**: Resource flow patterns"
    , "- **Diplomatic Intelligence**: Information from allies"
    , "- **Combat Results**: Ship origins from battle reports"
    , ""
    , "### Deception Detection"
    , "Recognize misdirection attempts:"
    , "- **False Trails**: Ships sent to mislead searchers"
    , "- **Decoy Bases**: Forward starbases mimicking homeworlds"
    , "- **Movement Patterns**: Deliberately confusing ship routes"
    , "- **Information Warfare**: False diplomatic intelligence"
    , ""
    , "## Practical Applications"
    , ""
    , "### Strategic Planning"
    , "Use homeworld intelligence for:"
    , "- **Alliance Strategy**: Coordinate with neighbors against distant threats"
    , "- **Economic Warfare**: Target enemy supply lines"
    , "- **Defensive Preparation**: Anticipate attack directions"
    , "- **Diplomatic Leverage**: Knowledge as bargaining power"
    , ""
    , "### Tactical Operations"
    , "Apply homeworld knowledge to:"
    , "- **Strike Planning**: Direct attacks on enemy power centers"
    , "- **Blockade Strategy**: Cut off homeworld supply lines"
    , "- **Diversion Tactics**: Force enemy fleet deployment"
    , "- **Territory Control**: Claim strategic positions"
    , ""
    , "## Remember"
    , ""
    , "Finding enemy homeworlds requires patience, systematic analysis,"
    , "and careful integration of multiple intelligence sources. The"
    , "galaxy's vastness protects homeworlds, but persistent"
    , "investigation will eventually reveal their secrets."
    , ""
    , "Use this knowledge wisely - in VGA Planets, information"
    , "is often more valuable than ships or planets."
    ]
