module Guide.Minefields where

minefieldsGuide :: String
minefieldsGuide = unlines
    [ "# VGA Planets Minefields Guide"
    , ""
    , "## Minefield Basics"
    , ""
    , "### What are Minefields?"
    , "Minefields are areas of space containing explosive devices that damage or destroy"
    , "ships passing through them. They're essential for area denial, defense, and"
    , "controlling strategic locations."
    , ""
    , "### Minefield Types"
    , "- **Standard Mines**: Damage any ship passing through"
    , "- **Web Mines**: Drain ship fuel and prevent movement (Crystal race only)"
    , "- **Deep Space Mines**: Laid by ships in open space"
    , "- **Planet-Based Mines**: Laid around planets for defense"
    , ""
    , "## Mine Laying"
    , ""
    , "### How to Lay Mines"
    , "1. **Ship Mission**: Set ship mission to 'Lay Mines'"
    , "2. **Torpedo Load**: Ship must carry torpedoes to convert to mines"
    , "3. **Conversion Rate**: Each torpedo type creates different numbers of mines"
    , "4. **Friendly Code**: Use 'mdX' codes for minefield control"
    , ""
    , "### Torpedo to Mine Conversion"
    , "- **Mark 1 Photon**: 1 torpedo = 1 mine"
    , "- **Proton Torpedo**: 1 torpedo = 2 mines"
    , "- **Gamma Bomb**: 1 torpedo = 3 mines"
    , "- **Mark 2 Photon**: 1 torpedo = 4 mines"
    , "- **Mark 4 Photon**: 1 torpedo = 5 mines"
    , "- **Mark 6 Photon**: 1 torpedo = 6 mines"
    , "- **Mark 7 Photon**: 1 torpedo = 7 mines"
    , "- **Mark 8 Photon**: 1 torpedo = 8 mines"
    , ""
    , "### Minefield Radius"
    , "Minefield radius = √(number of mines) light years"
    , "- 100 mines = 10 LY radius (314 square LY area)"
    , "- 400 mines = 20 LY radius (1,256 square LY area)"
    , "- 900 mines = 30 LY radius (2,827 square LY area)"
    , "- 2,500 mines = 50 LY radius (7,854 square LY area)"
    , ""
    , "## Minefield Mechanics"
    , ""
    , "### Hit Probability"
    , "Hit chance depends on ship mass and minefield density:"
    , "- **Light Ships** (< 100 kT): Higher hit probability"
    , "- **Medium Ships** (100-300 kT): Moderate hit probability"
    , "- **Heavy Ships** (> 300 kT): Lower hit probability"
    , "- **Formula**: Hit % = (Ship Mass / 100) × (Mine Density / 100)"
    , ""
    , "### Damage Calculation"
    , "When a ship hits mines:"
    , "- **Damage**: 10 + random(100) damage points"
    , "- **Mine Consumption**: 1 mine destroyed per hit"
    , "- **Multiple Hits**: Ships can hit multiple mines in one turn"
    , "- **Destruction**: Mines are removed when hit"
    , ""
    , "### Minefield Decay"
    , "- **Natural Decay**: 5% of mines are lost each turn"
    , "- **Minimum Loss**: At least 10 mines lost per turn (if minefield > 200 mines)"
    , "- **Small Fields**: Fields with < 100 mines decay faster"
    , ""
    , "## Minefield Strategy"
    , ""
    , "### Defensive Mining"
    , "- **Chokepoints**: Block narrow passages between star clusters"
    , "- **Planet Defense**: Surround important planets with mines"
    , "- **Starbase Protection**: Create defensive perimeters around starbases"
    , "- **Early Warning**: Use mines to detect enemy movement"
    , ""
    , "### Offensive Mining"
    , "- **Blockade**: Trap enemy fleets in mined areas"
    , "- **Supply Line Interdiction**: Mine enemy trade routes"
    , "- **Retreat Denial**: Mine areas where enemies might retreat"
    , "- **Force Concentration**: Channel enemies into kill zones"
    , ""
    , "### Minefield Maintenance"
    , "- **Regular Resupply**: Refresh mines to counter decay"
    , "- **Overlapping Fields**: Create redundant coverage"
    , "- **Mine Density**: Balance coverage vs. resource cost"
    , "- **Strategic Reserves**: Keep mine-laying ships ready"
    , ""
    , "## Web Mines (Crystal Confederation)"
    , ""
    , "### Web Mine Special Properties"
    , "- **Fuel Drain**: Ships lose fuel instead of taking damage"
    , "- **Movement Prevention**: Ships with < 50 fuel cannot move"
    , "- **No Ship Damage**: Web mines don't destroy ships directly"
    , "- **Crystal Immunity**: Crystal ships unaffected by all web mines"
    , ""
    , "### Web Mine Strategy"
    , "- **Area Denial**: Control large areas without ship destruction"
    , "- **Fleet Immobilization**: Strand enemy fleets without fuel"
    , "- **Capture Preparation**: Weaken enemies for boarding/assault"
    , "- **Defensive Barriers**: Create impassable zones"
    , ""
    , "### Web Mine Tactics"
    , "- **Layered Defense**: Combine web mines with standard mines"
    , "- **Fuel Trap**: Force enemies to burn fuel escaping"
    , "- **Carrier Counter**: Neutralize fighter-based strategies"
    , "- **Time Buying**: Delay enemy advances"
    , ""
    , "## Mine Sweeping"
    , ""
    , "### Beam Weapon Sweeping"
    , "- **Sweep Rate**: Each beam weapon destroys 4 mines per turn"
    , "- **Range**: Ship must be in minefield to sweep"
    , "- **Mission**: Set ship mission to 'Mine Sweep'"
    , "- **Safety**: Sweeping ships still risk mine hits"
    , ""
    , "### Fighter Sweeping"
    , "- **Carrier Advantage**: Fighters can sweep mines safely"
    , "- **Sweep Rate**: Each fighter squadron destroys 20 mines"
    , "- **Range**: Fighters can sweep adjacent areas"
    , "- **No Risk**: Fighters don't trigger mine hits"
    , ""
    , "### Specialized Sweepers"
    , "Some ship hulls have enhanced sweeping capabilities:"
    , "- **Improved Sweep Rate**: Double or triple normal rate"
    , "- **Reduced Hit Chance**: Lower probability of mine strikes"
    , "- **Extended Range**: Sweep mines from greater distance"
    , ""
    , "## Advanced Minefield Tactics"
    , ""
    , "### Minefield Combinations"
    , "- **Standard + Web**: Damage + immobilization"
    , "- **Overlapping Fields**: Multiple owners for redundancy"
    , "- **Mixed Densities**: Vary mine concentration for efficiency"
    , "- **Layered Defense**: Sequential minefields with gaps"
    , ""
    , "### Friendly Codes for Mining"
    , "- **md1-md9**: Specify which minefield to add mines to"
    , "- **mi1-mi9**: Specify which minefield to scoop mines from"
    , "- **NUK**: Nuclear torpedo for maximum mine laying"
    , "- **ATT**: Attack specific targets through minefields"
    , ""
    , "### Economic Considerations"
    , "- **Resource Cost**: Torpedoes are expensive (duranium, tritanium)"
    , "- **Opportunity Cost**: Ships laying mines aren't doing other missions"
    , "- **Maintenance**: Ongoing torpedo supply needed"
    , "- **ROI Calculation**: Defensive value vs. resource investment"
    , ""
    , "## Counter-Minefield Strategies"
    , ""
    , "### Avoiding Minefields"
    , "- **Sensor Sweep**: Detect minefields before entering"
    , "- **Route Planning**: Navigate around known minefields"
    , "- **Intelligence**: Use spies to reveal enemy mine locations"
    , "- **Sacrificial Scouts**: Use cheap ships to probe suspected areas"
    , ""
    , "### Clearing Minefields"
    , "- **Systematic Sweeping**: Use beam-armed ships to clear paths"
    , "- **Fighter Strikes**: Deploy carrier-based fighters"
    , "- **Overwhelming Force**: Accept losses to push through"
    , "- **Alternative Routes**: Find ways around mined areas"
    , ""
    , "### Minefield Intelligence"
    , "- **Detection Range**: Ships can see mines within 200 LY"
    , "- **Ownership**: Identify which race owns specific minefields"
    , "- **Size Estimation**: Judge minefield strength by radius"
    , "- **Age Assessment**: Older fields likely have lower density"
    , ""
    , "This comprehensive minefield guide covers all strategic and tactical"
    , "aspects of mine warfare in VGA Planets!"
    ]
