module Guide.Minefields where

minefieldsGuide :: String
minefieldsGuide = unlines
    [ "# VGA Planets Minefields Guide"
    , ""
    , "## Minefield Basics"
    , ""
    , "### What are Minefields?"
    , "Minefields are areas of space containing warheads that track and launch at enemy"
    , "starships passing through them. They're essential for area denial, defense, and"
    , "controlling strategic locations. Each minefield receives a unique Minefield ID."
    , ""
    , "### Minefield Types"
    , "- **Standard Mines**: Damage any ship passing through"
    , "- **Web Mines**: Drain ship fuel and prevent movement (Crystal race only)"
    , "- **Deep Space Mines**: Laid by ships in open space"
    , "- **Planet-Based Mines**: Laid around planets for defense"
    , ""
    , "## Mine Laying"
    , ""
    , "### How to Lay Mines"
    , "1. **Ship Mission**: Set ship mission to 'Lay Mines' or 'Lay Web Mines'"
    , "2. **Torpedo Load**: Ship must carry torpedoes to convert to mines"
    , "3. **Conversion Rate**: Torpedo tech level determines mine quantity and field size"
    , "4. **Friendly Code**: Use 'mdX' codes for minefield control"
    , "5. **Restrictions**: Cannot lay mines over star cluster cores or within 10 LY of them"
    , ""
    , "### Torpedo to Mine Conversion"
    , "- **Mark 1 Photon**: 1 torpedo = 1 mine"
    , "- **Proton Torpedo**: 1 torpedo = 2 mines"
    , "- **Gamma Bomb**: 1 torpedo = 3 mines"
    , "- **Mark 2 Photon**: 1 torpedo = 4 mines"
    , "- **Mark 4 Photon**: 1 torpedo = 5 mines"
    , "- **Mark 6 Photon**: 1 torpedo = 6 mines"
    , "- **Mark 7 Photon**: 1 torpedo = 7 mines"
    , "- **Mark 8 Photon**: 1 torpedo = 8 mines"
    , ""
    , "### Minefield Radius"
    , "Minefield radius = √(number of mines) light years"
    , "- 100 mines = 10 LY radius (314 square LY area)"
    , "- 400 mines = 20 LY radius (1,256 square LY area)"
    , "- 900 mines = 30 LY radius (2,827 square LY area)"
    , "- 2,500 mines = 50 LY radius (7,854 square LY area)"
    , ""
    , "## Minefield Mechanics"
    , ""
    , "### Hit Probability"
    , "- **Normal Mines**: 1% chance of hitting per light-year traveled"
    , "- **Cloaked Ships**: 0.5% chance of hitting per light-year traveled"
    , "- **Web Mines**: 5% chance of hitting per light-year traveled"
    , "- Mines distribute at 1 mine per 3.1416 square light-years"
    , "- Maximum minefield radius: 150 light-years (100 LY in Campaign mode)"
    , ""
    , "### Damage Calculation"
    , "When a ship hits mines:"
    , "- **Normal Mines**: Damage = 10000 / (Hull Mass + 1)"
    , "- **Web Mines**: Damage = 1000 / (Hull Mass + 1)"
    , "- **Mine Consumption**: 1 mine destroyed per hit"
    , "- **Multiple Hits**: Ships can hit multiple mines in one turn"
    , "- **Destruction**: Mines are removed when hit"
    , ""
    , "### Minefield Decay"
    , "- **Natural Decay**: ~5% of mines are lost each turn"
    , "- **Nebula Effect**: 15% decay rate in nebulae (triple normal rate)"
    , "- **Small Fields**: Fields with < 100 mines decay faster"
    , "- **Minimum Loss**: At least 10 mines lost per turn (if minefield > 200 mines)"
    , ""
    , "## Minefield Strategy"
    , ""
    , "### Defensive Mining"
    , "- **Chokepoints**: Block narrow passages between star clusters"
    , "- **Planet Defense**: Surround important planets with mines"
    , "- **Starbase Protection**: Create defensive perimeters around starbases"
    , "- **Early Warning**: Use mines to detect enemy movement"
    , ""
    , "### Offensive Mining"
    , "- **Blockade**: Trap enemy fleets in mined areas"
    , "- **Supply Line Interdiction**: Mine enemy trade routes"
    , "- **Retreat Denial**: Mine areas where enemies might retreat"
    , "- **Force Concentration**: Channel enemies into kill zones"
    , ""
    , "### Minefield Maintenance"
    , "- **Regular Resupply**: Refresh mines to counter decay"
    , "- **Overlapping Fields**: Create redundant coverage"
    , "- **Mine Density**: Balance coverage vs. resource cost"
    , "- **Strategic Reserves**: Keep mine-laying ships ready"
    , ""
    , "## Web Mines (Crystal Confederation)"
    , ""
    , "### Web Mine Special Properties"
    , "- **Fuel Drain**: Ships lose fuel and take damage (1000 / Hull Mass + 1)"
    , "- **Movement Stop**: Web mines instantly stop ship movement"
    , "- **Fuel Consumption**: Consumes ship's planned fuel for the turn"
    , "- **Shield Requirement**: Requires 50 KT or 1/6 fuel tank to maintain shields"
    , "- **Crystal Immunity**: Crystal ships unaffected by all web mines"
    , ""
    , "### Web Mine Strategy"
    , "- **Area Denial**: Control large areas without ship destruction"
    , "- **Fleet Immobilization**: Strand enemy fleets without fuel"
    , "- **Capture Preparation**: Weaken enemies for boarding/assault"
    , "- **Defensive Barriers**: Create impassable zones"
    , ""
    , "### Web Mine Tactics"
    , "- **Layered Defense**: Combine web mines with standard mines"
    , "- **Fuel Trap**: Force enemies to burn fuel escaping"
    , "- **Carrier Counter**: Neutralize fighter-based strategies"
    , "- **Time Buying**: Delay enemy advances"
    , ""
    , "## Mine Sweeping"
    , ""
    , "### Beam Weapon Sweeping"
    , "- **Sweep Rate**: Varies by beam weapon tech level:"
    , "  - Laser (Tech 1): 1 mine per beam per turn"
    , "  - X-Ray Laser (Tech 2): 2 mines per beam per turn"
    , "  - Plasma Bolt (Tech 3): 3 mines per beam per turn"
    , "  - Blaster (Tech 4): 4 mines per beam per turn"
    , "  - Positron Beam (Tech 5): 3 mines per beam per turn"
    , "  - Disruptor (Tech 6): 4 mines per beam per turn"
    , "  - Heavy Blaster (Tech 7): 7 mines per beam per turn"
    , "  - Phaser (Tech 8): 5 mines per beam per turn"
    , "  - Heavy Disruptor (Tech 9): 7 mines per beam per turn"
    , "  - Heavy Phaser (Tech 10): 6 mines per beam per turn"
    , "- **Range**: Ship must be within 5 light-years of minefield edge"
    , "- **Mission**: Set ship mission to 'Mine Sweep'"
    , "- **Safety**: Sweeping ships still risk mine hits while sweeping"
    , ""
    , "### Fighter Sweeping (Missing Colonies of Man Only)"
    , "- **Special Ability**: Only Missing Colonies fighters can sweep mines"
    , "- **Sweep Rate**: Each fighter destroys 20 mines per turn"
    , "- **Range**: Can sweep minefields within 100 light-years of carrier"
    , "- **Ion Storm Immunity**: Works even inside ion storms"
    , "- **Limitation**: Cannot sweep web mines, only normal mines"
    , ""
    , "### Starbase Mine Sweeping"
    , "Available to 9 races including Solar Federation and Cyborg:"
    , "- **Beam Sweeping**: Starbases can use beam weapons to sweep mines"
    , "- **Effectiveness**: Based on highest beam weapon tech level starbase can build"
    , "- **Range**: Same as ship sweeping (within 5 LY of minefield edge)"
    , "- **Both Mine Types**: Can sweep both normal mines and web mines"
    , ""
    , "## Advanced Minefield Tactics"
    , ""
    , "### Minefield Combinations"
    , "- **Standard + Web**: Damage + immobilization"
    , "- **Overlapping Fields**: Multiple owners for redundancy"
    , "- **Mixed Densities**: Vary mine concentration for efficiency"
    , "- **Layered Defense**: Sequential minefields with gaps"
    , ""
    , "### Friendly Codes for Mining"
    , "- **md1-md9**: Specify which minefield to add mines to"
    , "- **mi1-mi9**: Specify which minefield to scoop mines from"
    , "- **NUK**: Nuclear torpedo for maximum mine laying"
    , "- **ATT**: Attack specific targets through minefields"
    , ""
    , "### Economic Considerations"
    , "- **Resource Cost**: Torpedoes are expensive (duranium, tritanium)"
    , "- **Opportunity Cost**: Ships laying mines aren't doing other missions"
    , "- **Maintenance**: Ongoing torpedo supply needed"
    , "- **ROI Calculation**: Defensive value vs. resource investment"
    , ""
    , "## Counter-Minefield Strategies"
    , ""
    , "### Avoiding Minefields"
    , "- **Sensor Sweep**: Detect minefields before entering"
    , "- **Route Planning**: Navigate around known minefields"
    , "- **Intelligence**: Use spies to reveal enemy mine locations"
    , "- **Sacrificial Scouts**: Use cheap ships to probe suspected areas"
    , ""
    , "### Clearing Minefields"
    , "- **Systematic Sweeping**: Use beam-armed ships to clear paths"
    , "- **Fighter Strikes**: Deploy carrier-based fighters"
    , "- **Overwhelming Force**: Accept losses to push through"
    , "- **Alternative Routes**: Find ways around mined areas"
    , ""
    , "### Minefield Intelligence"
    , "- **Detection Range**: Ships can see mines within 200 LY"
    , "- **Ownership**: Identify which race owns specific minefields"
    , "- **Size Estimation**: Judge minefield strength by radius"
    , "- **Age Assessment**: Older fields likely have lower density"
    , ""
    , "### Minefield Limits and Overlapping"
    , "- **Game Limit**: Soft limit of 500 total minefields per game"
    , "- **Overlapping Fields**: Possible under certain diplomatic conditions"
    , "- **Friendly Codes**: Can provide safe passage through minefields"
    , "- **Starbase Mining**: In Campaign mode, starbases can also lay mines"
    , ""
    , "This comprehensive minefield guide covers all strategic and tactical"
    , "aspects of mine warfare in VGA Planets!"
    ]
