module Guide.Navigation where

navigationGuide :: String
navigationGuide = unlines
    [ "# VGA Planets Navigation Complete Guide"
    , ""
    , "## Navigation Fundamentals"
    , ""
    , "### Stellar Cartography Basics"
    , "The VGA Planets universe contains various navigational features:"
    , "- **Star Systems**: Planets orbiting stars"
    , "- **Open Space**: Empty areas between systems"
    , "- **Navigational Hazards**: Ion storms, warp wells, nebulae"
    , "- **Special Regions**: Star clusters, debris fields"
    , ""
    , "### Movement Mechanics"
    , "- **Warp Speed**: Ships travel at Warp 1-9"
    , "- **Fuel Consumption**: Higher warp = more fuel per light-year"
    , "- **Distance Formula**: Straight-line movement between coordinates"
    , "- **Turn-Based**: All movement occurs simultaneously each turn"
    , ""
    , "## Ion Storms"
    , ""
    , "### Ion Storm Characteristics"
    , "Ion storms are dangerous space phenomena that:"
    , "- **Move Constantly**: Travel at Warp 2-8 (usually Warp 6)"
    , "- **Grow and Shrink**: Voltage and radius change over time"
    , "- **Block Cloaking**: Ships cannot cloak inside ion storms"
    , "- **Damage Ships**: Cause electrical damage to vessels"
    , ""
    , "### Ion Storm Classes"
    , "- **Class 1**: 1-49 MeV, minor threat"
    , "- **Class 2**: 50-99 MeV, moderate danger"
    , "- **Class 3**: 100-149 MeV, serious hazard"
    , "- **Class 4**: 150-199 MeV, major threat"
    , "- **Class 5**: 200+ MeV, extreme danger"
    , ""
    , "### Ion Storm Effects"
    , "- **Electrical Damage**: Damages ship systems"
    , "- **Crew Casualties**: High-voltage storms kill crew"
    , "- **System Failures**: Ships may lose engines or weapons"
    , "- **Cloaking Disruption**: Impossible to cloak inside storms"
    , ""
    , "### Ion Storm Strategy"
    , "- **Avoidance**: Plot courses around storm paths"
    , "- **Prediction**: Estimate storm movement and growth"
    , "- **Emergency Escape**: Keep fuel reserves for evasive maneuvers"
    , "- **Tactical Use**: Use storms to block enemy cloaking"
    , ""
    , "## Warp Wells"
    , ""
    , "### Warp Well Mechanics"
    , "Warp wells are gravitational anomalies that:"
    , "- **Drain Fuel**: Increase fuel consumption significantly"
    , "- **Slow Movement**: Reduce effective warp speed"
    , "- **Planet-Based**: Usually associated with massive planets"
    , "- **Invisible**: Not directly visible on starmap"
    , ""
    , "### Warp Well Effects"
    , "- **Fuel Penalty**: 2x to 10x normal fuel consumption"
    , "- **Speed Reduction**: Maximum warp may be limited"
    , "- **Navigation Hazard**: Ships can become stranded"
    , "- **Strategic Barrier**: Create natural chokepoints"
    , ""
    , "### Warp Well Navigation"
    , "- **Detection**: Learn through experience and observation"
    , "- **Mapping**: Record well locations for future reference"
    , "- **Route Planning**: Plot efficient paths avoiding wells"
    , "- **Fuel Management**: Carry extra fuel when crossing wells"
    , ""
    , "## Stellar Cartography Features"
    , ""
    , "### Star Clusters"
    , "Special stellar formations containing:"
    , "- **Central Star**: Uninhabitable core star"
    , "- **Radiation Belt**: Damages ships approaching center"
    , "- **Crew Death**: Radiation kills ship crews and colonists"
    , "- **Impassable Core**: Destroys ships that reach center"
    , ""
    , "### Nebulae"
    , "Interstellar gas clouds that:"
    , "- **Hide Ships**: Reduce sensor range and detection"
    , "- **Hide Planets**: Conceal planetary locations"
    , "- **Navigation Difficulty**: Obscure long-range sensors"
    , "- **Tactical Advantage**: Enable surprise attacks"
    , ""
    , "### Debris Disks"
    , "Remnants of destroyed planets featuring:"
    , "- **Planetoids**: Small colonizable worlds"
    , "- **Mining Bases**: Can be built above planetoids"
    , "- **Scattered Resources**: Mineral deposits in debris"
    , "- **Navigation Hazards**: Dangerous to navigate"
    , ""
    , "### Cloudy Ion Storms"
    , "Advanced ion storm variants with:"
    , "- **Variable Strength**: Different voltage zones within storm"
    , "- **Multiple Centers**: Complex internal structure"
    , "- **Irregular Shape**: Non-circular boundaries"
    , "- **Unpredictable Movement**: Complex motion patterns"
    , ""
    , "## Navigation Planning"
    , ""
    , "### Route Optimization"
    , "- **Direct Path**: Shortest distance between points"
    , "- **Hazard Avoidance**: Route around dangerous areas"
    , "- **Fuel Efficiency**: Balance speed vs consumption"
    , "- **Time Constraints**: Consider mission urgency"
    , ""
    , "### Fleet Movement"
    , "- **Formation Keeping**: Coordinate multiple ship movement"
    , "- **Rendezvous Points**: Plan meeting locations"
    , "- **Escort Duties**: Protect slower vessels"
    , "- **Combat Approach**: Position for battle"
    , ""
    , "### Emergency Navigation"
    , "- **Fuel Crisis**: Find nearest refueling point"
    , "- **Storm Evasion**: Escape dangerous ion storms"
    , "- **Enemy Contact**: Evasive maneuvers"
    , "- **Rescue Operations**: Reach stranded vessels"
    , ""
    , "## Advanced Navigation Techniques"
    , ""
    , "### Gravitational Mechanics"
    , "- **Planetary Gravity**: Affects ship movement near planets"
    , "- **Slingshot Maneuvers**: Use gravity to save fuel"
    , "- **Orbital Mechanics**: Understand planetary motion"
    , "- **Tidal Forces**: Extreme gravity effects"
    , ""
    , "### Sensor Operations"
    , "- **Sensor Range**: Ships detect objects within 200 LY"
    , "- **Sensor Sweep**: Mission to detect cloaked ships"
    , "- **Long Range Sensors**: Extended detection capabilities"
    , "- **Sensor Jamming**: Nebulae and storms block sensors"
    , ""
    , "### Cloaking and Detection"
    , "- **Cloak Navigation**: Move while remaining hidden"
    , "- **Decloak Points**: Strategic locations to reveal"
    , "- **Detection Avoidance**: Stay beyond sensor range"
    , "- **Counter-Detection**: Find cloaked enemies"
    , ""
    , "## Navigation Tools and Resources"
    , ""
    , "### Starmap Features"
    , "- **Coordinate System**: X,Y positioning"
    , "- **Distance Measurement**: Calculate travel distances"
    , "- **Zoom Levels**: Different detail views"
    , "- **Overlay Information**: Show additional data"
    , ""
    , "### Navigation Aids"
    , "- **Waypoint System**: Plan multi-stop journeys"
    , "- **Course Plotting**: Visual route planning"
    , "- **Fuel Calculators**: Estimate consumption"
    , "- **Travel Time**: Calculate arrival turns"
    , ""
    , "### External Tools"
    , "- **Third-Party Maps**: Enhanced mapping tools"
    , "- **Route Planners**: Optimized path finding"
    , "- **Fuel Calculators**: Precise consumption estimates"
    , "- **Storm Trackers**: Ion storm prediction tools"
    , ""
    , "## Strategic Navigation"
    , ""
    , "### Territory Control"
    , "- **Chokepoint Control**: Dominate key passages"
    , "- **Border Defense**: Monitor frontier regions"
    , "- **Supply Lines**: Maintain resource flow"
    , "- **Retreat Routes**: Plan emergency escape paths"
    , ""
    , "### Intelligence Gathering"
    , "- **Scout Networks**: Position detection ships"
    , "- **Patrol Routes**: Regular surveillance patterns"
    , "- **Early Warning**: Detect enemy movement"
    , "- **Reconnaissance**: Gather tactical information"
    , ""
    , "### Operational Security"
    , "- **Route Variation**: Change paths to avoid predictability"
    , "- **Deception**: False movements to confuse enemies"
    , "- **Communication Security**: Avoid revealing positions"
    , "- **Stealth Movement**: Use cloaking and cover"
    , ""
    , "This comprehensive navigation guide covers all aspects of"
    , "movement and spatial awareness in VGA Planets!"
    ]