module Guide.Overall where

gameGuideContent :: String
gameGuideContent = unlines
    [ "# VGA Planets Complete Game Guide"
    , ""
    , "## Game Overview"
    , "VGA Planets is a multiplayer turn-based space strategy game. Typically 11 players each control a unique race."
    , "Players start with a planet, starbase, and ship. The goal is economic and military expansion through mining,"
    , "colonization, starship construction, and planetary resource management."
    , ""
    , "## The 11 Races and Their Special Abilities"
    , ""
    , "### 1. Solar Federation (The Feds)"
    , "- **Tax Bonus**: 200% tax rate, effectively doubling their tax base"
    , "- **Fed Crew Bonus**: +50 kT hull mass, +3 fighter bays, +25% shield regen, all weapons remain available"
    , "- **Penalty**: 70% mining efficiency due to environmental laws"
    , "- **Strategy**: Torpedo-focused race with powerful economic base"
    , "- **Key Ships**: Nova Class Super-dreadnought, Kittyhawk Class Carrier"
    , ""
    , "### 2. Lizard Alliance"
    , "- **Ground Combat**: 30:1 attack, 15:1 defense - strongest in game"
    , "- **Mining Bonus**: 2x faster mining"
    , "- **Hiss Mission**: Improves planet economy"
    , "- **Lizard Crew Bonus**: Ships take 150% damage, ignore first 50% engine/weapon damage"
    , "- **Strategy**: Early aggressive expansion through ground assault"
    , ""
    , "### 3. Empire of Birds (Birdmen)"
    , "- **Cloaking**: Large fleet of cloaking ships including Dark Wing battleship"
    , "- **Super Spy Mission**: Reveals planet defenses, can change enemy friendly codes"
    , "- **Strategy**: Stealth attacks, intelligence superiority"
    , "- **Key Ships**: Dark Wing Class Battleship (only cloaking battleship)"
    , ""
    , "### 4. Fascist Empire"
    , "- **Pillage Mission**: Steal supplies from planets"
    , "- **Glory Device**: Ships can self-destruct for massive damage"
    , "- **Rebel Ground Combat**: Strong against rebels"
    , "- **Strategy**: Aggressive warfare and resource theft"
    , ""
    , "### 5. Privateer Bands"
    , "- **Rob Mission**: Steal money from enemy ships"
    , "- **Boarding**: Capture enemy ships"
    , "- **Gambling**: Can convert supplies to money"
    , "- **Strategy**: Economic warfare through theft and capture"
    , ""
    , "### 6. Cyborg"
    , "- **Assimilation**: Convert enemy ships and planets"
    , "- **Self Repair**: Ships repair themselves"
    , "- **Chunnel**: Instant ship transport between starbases"
    , "- **Native Tax Limit**: Max 20% native tax efficiency"
    , "- **Strategy**: Technology and assimilation focus"
    , ""
    , "### 7. Crystal Confederation"
    , "- **Web Mines**: Create area denial minefields"
    , "- **Desert Advantage**: Thrive on desert planets"
    , "- **Crystal Thunder Class**: Web-laying battleship"
    , "- **Strategy**: Defensive minefield control"
    , ""
    , "### 8. Evil Empire"
    , "- **Dark Sense**: Detect cloaked ships"
    , "- **Imperial Assault**: Enhanced ground combat"
    , "- **Strategy**: Anti-cloaking specialists"
    , ""
    , "### 9. Robotic Imperium"
    , "- **Self-Repairing**: Ships repair damage automatically"
    , "- **Mining Bonus**: Efficient resource extraction"
    , "- **Strategy**: Industrial powerhouse"
    , ""
    , "### 10. Rebel Confederation"
    , "- **Rebel Ground Combat**: Strong defensive capabilities"
    , "- **Strategy**: Defensive specialists"
    , ""
    , "### 11. Missing Colonies of Man"
    , "- **Cloaking**: Ships can cloak"
    , "- **Strategy**: Stealth operations"
    , ""
    , "## Taxation and Economics"
    , ""
    , "### Taxation Rules"
    , "- Tax colonists and natives separately"
    , "- Happiness below 31: No tax income"
    , "- Happiness below 0: Civil war begins"
    , "- Maximum 5,000 MegaCredits per planet per turn"
    , "- Most natives: 1 MC per colonist clan"
    , "- Insectoids: 2 MC per colonist clan"
    , ""
    , "### Taxation Strategies"
    , "1. **Safe Taxing**: Tax to maintain happiness (moderate growth)"
    , "2. **Growth Taxing**: Tax heavily to 70 happiness, then 0% tax for recovery"
    , ""
    , "### Building Destruction"
    , "- Below 40 happiness: 8 factories + 10 mines destroyed per turn"
    , "- Combined colonist/native taxation: 11 factories + 15 mines destroyed"
    , ""
    , "## Ship Design and Combat"
    , ""
    , "### Hull Components"
    , "- **Hull Mass**: Base ship weight"
    , "- **Max Fuel**: Fuel tank capacity"
    , "- **Max Cargo**: Cargo hold capacity"
    , "- **Fighter Bays**: Number of fighter squadrons"
    , "- **Beam Weapons**: Number of beam weapon slots"
    , "- **Torpedo Tubes**: Number of torpedo launchers"
    , ""
    , "### Engine Technology (Tech 1-10)"
    , "- StarDrive 1 (Tech 1): Efficient at Warp 1"
    , "- Transwarp Drive (Tech 10): Efficient at Warp 9"
    , "- Higher tech = better fuel efficiency at high warp"
    , ""
    , "### Beam Weapons (Tech 1-10)"
    , "1. Laser (Tech 1)"
    , "2. X-Ray Laser (Tech 1)"
    , "3. Plasma Bolt (Tech 2)"
    , "4. Blaster (Tech 3)"
    , "5. Positron Beam (Tech 4)"
    , "6. Disruptor (Tech 5)"
    , "7. Heavy Blaster (Tech 6)"
    , "8. Phaser (Tech 7)"
    , "9. Heavy Disruptor (Tech 8)"
    , "10. Heavy Phaser (Tech 10)"
    , ""
    , "### Torpedo Systems (Tech 1-10)"
    , "- **Mark 1-10**: Increasing damage and mine-laying capability"
    , "- **Gamma Bombs (Tech 3)**: Specialty for ship capture"
    , "- **Mark 4 (Tech 5)**: Most cost-efficient"
    , "- **Mark 8 (Tech 10)**: Highest damage"
    , ""
    , "### Combat Mechanics"
    , "- Beam weapons draw power from engines"
    , "- Torpedoes most powerful weapon system"
    , "- Fighters have longest range"
    , "- Shield penetration affects crew kills"
    , ""
    , "## Planetary Management"
    , ""
    , "### Climate and Growth"
    , "- Temperature affects colonist growth rates"
    , "- Optimal temperature varies by race"
    , "- Terraforming possible with certain hulls"
    , ""
    , "### Native Types and Benefits"
    , "- **Humanoids**: Standard taxation"
    , "- **Bovinoids**: Mining bonus"
    , "- **Reptilians**: Taxation bonus"
    , "- **Avians**: Taxation bonus"
    , "- **Amorphous**: Cannot be taxed"
    , "- **Insectoids**: 2x taxation rate"
    , "- **Amphibians**: Taxation bonus"
    , "- **Ghipsoldals**: Taxation bonus"
    , "- **Siliconoids**: Mining bonus"
    , ""
    , "### Mining and Production"
    , "- Tritanium, Duranium, Molybdenum minerals"
    , "- Supplies produced by factories"
    , "- Mines extract minerals based on density"
    , "- More buildings = lower happiness"
    , ""
    , "## Starbase Operations"
    , ""
    , "### Tech Levels"
    , "- Hull Tech: Available ship designs"
    , "- Engine Tech: Engine types"
    , "- Beam Tech: Weapon systems"
    , "- Torpedo Tech: Torpedo types"
    , ""
    , "### Starbase Missions"
    , "- Ship construction"
    , "- Ship repair"
    , "- Tech upgrades"
    , "- Defense (base fighters and defense posts)"
    , ""
    , "## Strategic Tips"
    , ""
    , "### Early Game (Turns 1-30)"
    , "- Explore and colonize nearby planets"
    , "- Build economy before military"
    , "- Establish supply lines"
    , "- Scout for enemy positions"
    , ""
    , "### Mid Game (Turns 30-60)"
    , "- Tech up for better ships"
    , "- Form alliances"
    , "- Control strategic resources"
    , "- Build fleet strength"
    , ""
    , "### Late Game (Turns 60+)"
    , "- Major fleet battles"
    , "- Territory consolidation"
    , "- Economic warfare"
    , "- Victory conditions"
    , ""
    , "## Victory Conditions"
    , "- Control majority of universe"
    , "- Economic dominance"
    , "- Military supremacy"
    , "- Alliance victory"
    , ""
    , "This guide covers the essential mechanics of VGA Planets. Master these concepts"
    , "to dominate the galaxy!"
    ]
