module Guide.Races where

racesGuide :: String
racesGuide = unlines
    [ "# VGA Planets Races Complete Guide"
    , ""
    , "## The 11 Races Overview"
    , "Each race in VGA Planets has unique abilities, ship designs, and strategic advantages."
    , "Understanding racial abilities is crucial for both playing as and against each race."
    , ""
    , "## 1. Solar Federation (The Feds)"
    , ""
    , "### Special Abilities"
    , "- **Super Refit**: Can refit any ship at any starbase, regardless of tech levels"
    , "- **200% Tax Rate**: Doubles tax income from both colonists and natives"
    , "- **Fed Crew Bonus**: Ships get +50 kT mass, +3 fighter bays, +25% shield regen, all weapons remain functional"
    , "- **Penalty**: Only 70% mining efficiency due to environmental protection laws"
    , ""
    , "### Strategy"
    , "- Economic powerhouse with massive tax income"
    , "- Torpedo-focused race with excellent medium warships"
    , "- Build economy first, then transition to military production"
    , "- Use Super Refit to quickly upgrade ship designs"
    , ""
    , "### Key Ships"
    , "- **Nova Class Super-dreadnought**: 8 beams, 10 torpedo tubes, excellent flagship"
    , "- **Kittyhawk Class Carrier**: 6 fighter bays (9 with crew bonus)"
    , "- **Nocturne Class Destroyer**: Fast, cheap torpedo ship"
    , ""
    , "## 2. Lizard Alliance"
    , ""
    , "### Special Abilities"
    , "- **Ground Combat**: 30:1 attack ratio, 15:1 defense ratio (strongest in game)"
    , "- **2x Mining Speed**: Extract minerals twice as fast"
    , "- **Hiss Mission**: Increases happiness and tax income on planets"
    , "- **Lizard Crew Bonus**: Ships can take 150% damage, ignore first 50% engine/weapon damage"
    , ""
    , "### Strategy"
    , "- Ultimate early-game aggressive race"
    , "- Capture enemy planets through ground assault"
    , "- Rush expansion in first 30 turns"
    , "- Use superior mining to fuel rapid growth"
    , ""
    , "### Key Ships"
    , "- **T-Rex Class Battleship**: Strong medium battleship"
    , "- **Lizard Class Cruiser**: Fast raider with good cargo capacity"
    , "- **Madonnzila Class Carrier**: Their only carrier design"
    , ""
    , "## 3. Empire of Birds (Birdmen)"
    , ""
    , "### Special Abilities"
    , "- **Advanced Cloaking**: Large fleet of cloaking ships"
    , "- **Super Spy Mission**: Reveals planet defenses, changes enemy friendly codes"
    , "- **Sensor Sweep**: Reveals cloaked ships in area"
    , "- **Dark Sense**: Can detect cloaked enemy ships"
    , ""
    , "### Strategy"
    , "- Masters of stealth and intelligence warfare"
    , "- Pick off isolated enemy ships and planets"
    , "- Use Super Spy to steal resources and bypass defenses"
    , "- Avoid direct fleet confrontations"
    , ""
    , "### Key Ships"
    , "- **Dark Wing Class Battleship**: Only cloaking battleship in game"
    , "- **Bright Heart Class Destroyer**: Cloaking torpedo ship"
    , "- **Fearless Wing Cruiser**: Fast cloaking scout"
    , ""
    , "## 4. Fascist Empire"
    , ""
    , "### Special Abilities"
    , "- **Pillage Mission**: Steal supplies from enemy planets"
    , "- **Glory Device**: Ships can self-destruct for massive area damage"
    , "- **Rebel Ground Combat**: +10 advantage against Rebel race"
    , "- **Imperial Assault**: Enhanced ground combat on certain planets"
    , ""
    , "### Strategy"
    , "- Aggressive warfare and resource denial"
    , "- Use Glory Device tactically to eliminate enemy fleets"
    , "- Pillage enemy economies to fuel your own growth"
    , "- Strong early-mid game military force"
    , ""
    , "### Key Ships"
    , "- **Victorious Class Battleship**: Well-armed general purpose battleship"
    , "- **D19b Nefarious Class Destroyer**: Cheap, fast raider"
    , "- **Little Pest Class Escort**: Small ship perfect for Glory Device attacks"
    , ""
    , "## 5. Privateer Bands"
    , ""
    , "### Special Abilities"
    , "- **Rob Mission**: Steal money from enemy ships"
    , "- **Boarding Party**: Capture weakened enemy ships"
    , "- **Gambling**: Convert supplies to money (and vice versa)"
    , "- **Piracy**: No fuel cost for certain ship missions"
    , ""
    , "### Strategy"
    , "- Economic warfare through theft and piracy"
    , "- Build large fleets of cheap ships"
    , "- Focus on capturing enemy vessels"
    , "- Use gambling to balance resources"
    , ""
    , "### Key Ships"
    , "- **Meteor Class Blockade Runner**: Fast cargo ship, perfect for hit-and-run"
    , "- **Lady Royale Class Gambling Cruiser**: Mobile casino and command ship"
    , "- **Br4 Class Gunship**: Cheap, expendable combat vessel"
    , ""
    , "## 6. Cyborg"
    , ""
    , "### Special Abilities"
    , "- **Assimilation**: Convert enemy ships and planets to Cyborg control"
    , "- **Self Repair**: Ships automatically repair 5% damage per turn"
    , "- **Chunnel**: Instant transport between Firecloud Class ships"
    , "- **Native Tax Limitation**: Maximum 20% tax efficiency from natives"
    , ""
    , "### Strategy"
    , "- Technology-focused race with unique logistics"
    , "- Use Chunnel for rapid fleet deployment"
    , "- Assimilate enemy assets rather than destroying them"
    , "- Strong late-game potential"
    , ""
    , "### Key Ships"
    , "- **Annihilation Class Battleship**: Heaviest ship in game"
    , "- **Firecloud Class Cruiser**: Chunnel-capable workhorse"
    , "- **Probe Class Escort**: Small, cheap assimilation vessel"
    , ""
    , "## 7. Crystal Confederation"
    , ""
    , "### Special Abilities"
    , "- **Web Mines**: Create area-denial minefields"
    , "- **Desert Advantage**: No penalty on desert planets, bonus fighter production"
    , "- **Crystalline Web**: Enhanced minefield control"
    , "- **Web Immunity**: Ships unaffected by web mines"
    , ""
    , "### Strategy"
    , "- Defensive specialists using minefield control"
    , "- Control key strategic locations with web mines"
    , "- Excel on desert planets"
    , "- Support allies with defensive minefields"
    , ""
    , "### Key Ships"
    , "- **Crystal Thunder Class Battleship**: Web-laying battleship"
    , "- **Emerald Class Battlecruiser**: Fast, well-armed web-layer"
    , "- **Diamond Flame Class Battleship**: Heavy combat vessel"
    , ""
    , "## 8. Evil Empire"
    , ""
    , "### Special Abilities"
    , "- **Dark Sense**: Automatically detect cloaked ships"
    , "- **Imperial Assault**: Enhanced ground combat capabilities"
    , "- **Probe Mission**: Gather intelligence on enemy planets"
    , "- **Death Ray**: Destroy planet populations"
    , ""
    , "### Strategy"
    , "- Anti-cloaking specialists"
    , "- Strong military with good detection capabilities"
    , "- Use Death Ray strategically to deny enemy resources"
    , "- Excel against stealthy opponents"
    , ""
    , "### Key Ships"
    , "- **Super Star Destroyer**: Massive flagship with Death Ray"
    , "- **Super Star Frigate**: Well-balanced medium warship"
    , "- **Deth Specula Class Frigate**: Fast anti-cloaking vessel"
    , ""
    , "## 9. Robotic Imperium"
    , ""
    , "### Special Abilities"
    , "- **Self-Repairing Ships**: Automatic damage repair each turn"
    , "- **Mining Robots**: Enhanced mineral extraction"
    , "- **Build Fighters**: Can construct fighters without carriers"
    , "- **Efficient Production**: Reduced build costs for certain items"
    , ""
    , "### Strategy"
    , "- Industrial powerhouse with excellent economy"
    , "- Build massive fleets through efficient production"
    , "- Use self-repair to maintain fleet strength"
    , "- Focus on resource control and production"
    , ""
    , "### Key Ships"
    , "- **Golem Class Battleship**: Heavily armored self-repairing battleship"
    , "- **Cat's Paw Class Destroyer**: Fast, cheap patrol vessel"
    , "- **Instrumentality Class Baseship**: Massive carrier/battleship hybrid"
    , ""
    , "## 10. Rebel Confederation"
    , ""
    , "### Special Abilities"
    , "- **Rebel Ground Combat**: Strong defensive ground combat"
    , "- **Planetary Defense**: Enhanced starbase and planetary defenses"
    , "- **Guerrilla Warfare**: Bonus when fighting on own planets"
    , "- **Fast Build**: Reduced construction times for certain ships"
    , ""
    , "### Strategy"
    , "- Defensive specialists with strong home advantage"
    , "- Build strong defensive positions"
    , "- Use guerrilla tactics against invaders"
    , "- Excel at holding territory"
    , ""
    , "### Key Ships"
    , "- **Patriot Class Light Carrier**: Versatile light carrier"
    , "- **Falcon Class Escort**: Fast, maneuverable patrol ship"
    , "- **Rush Class Destroyer**: Quick-build combat vessel"
    , ""
    , "## 11. Missing Colonies of Man"
    , ""
    , "### Special Abilities"
    , "- **Cloaking Device**: Many ships can cloak"
    , "- **Colonial Fighter**: Enhanced fighter combat"
    , "- **Salvage Mission**: Recover materials from battle debris"
    , "- **Emergency Repair**: Field repair capabilities"
    , ""
    , "### Strategy"
    , "- Balanced race with stealth capabilities"
    , "- Use cloaking for reconnaissance and surprise attacks"
    , "- Salvage operations to supplement economy"
    , "- Flexible tactical options"
    , ""
    , "### Key Ships"
    , "- **Virgo Class Battlestar**: Large carrier-battleship"
    , "- **Gemini Class Transport**: Cloaking cargo vessel"
    , "- **Sagittarius Class Transport**: Heavy cargo with some combat ability"
    , ""
    , "## Race Matchups and Alliances"
    , ""
    , "### Strong Against"
    , "- **Federation**: Strong vs. economic races, weak vs. early rushers"
    , "- **Lizards**: Dominant early game, vulnerable late game"
    , "- **Birds**: Excel vs. non-cloaking races, struggle vs. Evil Empire"
    , "- **Crystals**: Defensive powerhouse, needs aggressive allies"
    , ""
    , "### Recommended Alliances"
    , "- **Fed + Crystals**: Economic power + defensive control"
    , "- **Birds + Privateers**: Stealth + economic warfare"
    , "- **Lizards + Fascists**: Double early game aggression"
    , "- **Cyborg + Robots**: Technology and production focus"
    , ""
    , "This comprehensive race guide covers all strategic essentials for mastering"
    , "each faction in VGA Planets!"
    ]
