module Guide.Ships where

shipsGuide :: String
shipsGuide = unlines
    [ "# VGA Planets Ships and Combat Guide"
    , ""
    , "## Ship Design Fundamentals"
    , ""
    , "### Hull Components"
    , "- **Hull Mass**: Base weight of ship without equipment (affects fuel efficiency)"
    , "- **Cargo Capacity**: Space for minerals, supplies, colonists, and fuel"
    , "- **Fuel Tank**: Maximum fuel capacity for movement and combat"
    , "- **Crew**: Ship's personnel (affects combat effectiveness and special abilities)"
    , "- **Fighter Bays**: Number of fighter squadrons the ship can carry"
    , "- **Beam Weapons**: Number of energy weapon mounts"
    , "- **Torpedo Tubes**: Number of torpedo/missile launchers"
    , ""
    , "### Ship Classifications"
    , ""
    , "#### Scouts and Escorts (50-150 kT)"
    , "- **Purpose**: Exploration, early colonization, small raids"
    , "- **Typical Loadout**: 1-2 beams, 0-1 torpedo tubes"
    , "- **Examples**: Small Deep Space Freighter, Outrider Class Scout"
    , "- **Cost**: 20-50 MegaCredits"
    , ""
    , "#### Destroyers (150-250 kT)"
    , "- **Purpose**: Fast attack, patrol, convoy escort"
    , "- **Typical Loadout**: 4 beams, 2 torpedo tubes"
    , "- **Examples**: Nocturne Class, D19b Nefarious"
    , "- **Cost**: 60-120 MegaCredits"
    , ""
    , "#### Light Cruisers (250-350 kT)"
    , "- **Purpose**: Multi-role combat, cargo escort"
    , "- **Typical Loadout**: 6 beams, 3 torpedo tubes"
    , "- **Examples**: Meteor Class, Bright Heart Class"
    , "- **Cost**: 100-200 MegaCredits"
    , ""
    , "#### Heavy Cruisers (350-450 kT)"
    , "- **Purpose**: Fleet support, independent operations"
    , "- **Typical Loadout**: 8 beams, 4 torpedo tubes"
    , "- **Examples**: Firecloud Class, Emerald Class"
    , "- **Cost**: 180-300 MegaCredits"
    , ""
    , "#### Battleships (450+ kT)"
    , "- **Purpose**: Fleet flagship, heavy combat"
    , "- **Typical Loadout**: 10 beams, 6+ torpedo tubes"
    , "- **Examples**: Nova Class, Dark Wing Class, Annihilation Class"
    , "- **Cost**: 400-800+ MegaCredits"
    , ""
    , "#### Carriers (300+ kT)"
    , "- **Purpose**: Fighter operations, long-range combat"
    , "- **Typical Loadout**: 4-6 beams, 4-10 fighter bays"
    , "- **Examples**: Kittyhawk Class, Virgo Class Battlestar"
    , "- **Cost**: 300-600 MegaCredits"
    , ""
    , "## Engine Technology"
    , ""
    , "### Engine Types (Tech Level 1-10)"
    , "1. **StarDrive 1** (Tech 1): Efficient at Warp 1, 100 fuel per LY at Warp 9"
    , "2. **Quick Jump 5** (Tech 2): Efficient at Warp 2, 84 fuel per LY at Warp 9"
    , "3. **Fuel Saver** (Tech 3): Efficient at Warp 3, 72 fuel per LY at Warp 9"
    , "4. **Long Range 8** (Tech 4): Efficient at Warp 4, 62 fuel per LY at Warp 9"
    , "5. **Heavy Blast 9** (Tech 5): Efficient at Warp 5, 54 fuel per LY at Warp 9"
    , "6. **Quantam 7** (Tech 6): Efficient at Warp 6, 48 fuel per LY at Warp 9"
    , "7. **HyperDrive 6** (Tech 7): Efficient at Warp 7, 43 fuel per LY at Warp 9"
    , "8. **Nova Drive 5** (Tech 8): Efficient at Warp 8, 38 fuel per LY at Warp 9"
    , "9. **Quantam 8** (Tech 9): Efficient at Warp 8.5, 35 fuel per LY at Warp 9"
    , "10. **Transwarp Drive** (Tech 10): Efficient at Warp 9, 32 fuel per LY at Warp 9"
    , ""
    , "### Engine Selection Strategy"
    , "- **Early Game**: Use Tech 1-3 engines (cheap, adequate for short distances)"
    , "- **Mid Game**: Upgrade to Tech 6-8 (balance of cost and efficiency)"
    , "- **Late Game**: Transwarp Drive for maximum efficiency"
    , "- **Special Cases**: Match engine to typical operating warp speed"
    , ""
    , "## Weapon Systems"
    , ""
    , "### Beam Weapons (Tech Level 1-10)"
    , "1. **Laser** (Tech 1): 1 damage, 1 kill, 1 MC cost"
    , "2. **X-Ray Laser** (Tech 1): 1 damage, 1 kill, 1 MC cost"
    , "3. **Plasma Bolt** (Tech 2): 3 damage, 2 kill, 2 MC cost"
    , "4. **Blaster** (Tech 3): 4 damage, 3 kill, 5 MC cost"
    , "5. **Positron Beam** (Tech 4): 7 damage, 5 kill, 12 MC cost"
    , "6. **Disruptor** (Tech 5): 10 damage, 6 kill, 13 MC cost"
    , "7. **Heavy Blaster** (Tech 6): 13 damage, 8 kill, 31 MC cost"
    , "8. **Phaser** (Tech 7): 16 damage, 10 kill, 35 MC cost"
    , "9. **Heavy Disruptor** (Tech 8): 20 damage, 12 kill, 36 MC cost"
    , "10. **Heavy Phaser** (Tech 10): 35 damage, 20 kill, 54 MC cost"
    , ""
    , "### Torpedo Systems (Tech Level 1-10)"
    , "1. **Mark 1 Photon** (Tech 1): 5 damage, 4 kill, 1 mine"
    , "2. **Proton Torpedo** (Tech 2): 8 damage, 4 kill, 2 mines"
    , "3. **Gamma Bomb** (Tech 3): 10 damage, 25 kill, 3 mines (special: high crew kill)"
    , "4. **Mark 2 Photon** (Tech 4): 15 damage, 7 kill, 4 mines"
    , "5. **Mark 4 Photon** (Tech 5): 20 damage, 10 kill, 5 mines (most cost-efficient)"
    , "6. **Mark 6 Photon** (Tech 6): 25 damage, 13 kill, 6 mines"
    , "7. **Mark 7 Photon** (Tech 7): 30 damage, 16 kill, 7 mines"
    , "8. **Mark 8 Photon** (Tech 8): 55 damage, 35 kill, 8 mines (highest damage)"
    , "9. **-(no tech 9 torpedo)**"
    , "10. **-(no tech 10 torpedo)**"
    , ""
    , "### Weapon Selection Strategy"
    , "- **Beam Weapons**: Heavy Phaser for maximum damage, Disruptor for cost efficiency"
    , "- **Torpedoes**: Mark 4 for cost efficiency, Mark 8 for damage, Gamma Bombs for capture"
    , "- **Mixed Loadouts**: Balance beam and torpedo weapons based on role"
    , ""
    , "## Ship Construction"
    , ""
    , "### Build Requirements"
    , "- **Starbase**: Required for all ship construction"
    , "- **Tech Levels**: Hull, Engine, Beam, and Torpedo tech must meet requirements"
    , "- **Materials**: Tritanium, Duranium, Molybdenum based on design"
    , "- **Money**: MegaCredits for labor and components"
    , "- **Time**: One turn per ship (with exceptions)"
    , ""
    , "### Build Optimization"
    , "- **Priorities**: Essential ships first (scouts, freighters, defenders)"
    , "- **Tech Progression**: Upgrade tech levels strategically"
    , "- **Resource Management**: Balance material costs across multiple builds"
    , "- **Fleet Composition**: Mix of ship types for different roles"
    , ""
    , "## Combat Mechanics"
    , ""
    , "### Battle Sequence"
    , "1. **Fighter Phase**: Fighters attack enemy ships"
    , "2. **Torpedo Phase**: Ships fire torpedoes at enemy ships"
    , "3. **Beam Phase**: Ships fire beam weapons at enemy ships/fighters"
    , "4. **Damage Resolution**: Apply damage to shields, then hull"
    , "5. **Crew Kill**: Resolve crew casualties"
    , "6. **Repeat**: Until one side is eliminated or retreats"
    , ""
    , "### Combat Factors"
    , "- **Shield Strength**: Absorbs damage before hull takes hits"
    , "- **Hull Damage**: Reduces ship effectiveness and crew"
    , "- **Crew Level**: Affects weapon accuracy and special abilities"
    , "- **Experience**: Veteran crews fight more effectively"
    , "- **Special Abilities**: Race-specific combat bonuses"
    , ""
    , "### Damage Effects"
    , "- **0-20% Damage**: No effect on performance"
    , "- **21-50% Damage**: Reduced weapon effectiveness"
    , "- **51-99% Damage**: Severely reduced effectiveness"
    , "- **100% Damage**: Ship destroyed"
    , ""
    , "## Ship Missions"
    , ""
    , "### Standard Missions"
    , "- **Explore**: Reveals map details and planet information"
    , "- **Mine Sweep**: Destroys enemy mines in area"
    , "- **Lay Mines**: Creates defensive/offensive minefields"
    , "- **Kill**: Attacks enemy ships and planets"
    , "- **Sensor Sweep**: Detects cloaked ships and planets"
    , "- **Colonize**: Establishes colonies on uninhabited planets"
    , "- **Beam Up/Down**: Transfers cargo and personnel"
    , ""
    , "### Special Missions (Race-Specific)"
    , "- **Super Spy** (Birds): Intelligence gathering and sabotage"
    , "- **Hiss** (Lizards): Improves planet happiness and economy"
    , "- **Rob** (Privateers): Steals money from enemy ships"
    , "- **Pillage** (Fascists): Steals supplies from enemy planets"
    , "- **Cloak** (Various): Renders ship invisible to most detection"
    , ""
    , "## Fleet Tactics"
    , ""
    , "### Fleet Composition"
    , "- **Balanced Fleet**: Mix of carriers, battleships, and support ships"
    , "- **Carrier Group**: Carriers protected by escort vessels"
    , "- **Battleship Squadron**: Heavy firepower for direct assault"
    , "- **Raider Group**: Fast ships for hit-and-run attacks"
    , ""
    , "### Tactical Considerations"
    , "- **Range**: Fighters > Torpedoes > Beam Weapons"
    , "- **Positioning**: Control engagement range and timing"
    , "- **Support**: Coordinate with allies and defensive installations"
    , "- **Logistics**: Maintain fuel and supply lines"
    , ""
    , "This comprehensive ship guide covers all aspects of naval warfare"
    , "in VGA Planets!"
    ]
