module Guide.Starbases where

starbasesGuide :: String
starbasesGuide = unlines
    [ "# VGA Planets Starbases Complete Guide"
    , ""
    , "## Starbase Fundamentals"
    , ""
    , "### What are Starbases?"
    , "Starbases are massive orbital installations that serve as:"
    , "- **Ship Construction Centers**: Build and refit starships"
    , "- **Technology Research Hubs**: Advance tech levels"
    , "- **Defense Platforms**: Protect planets with fighters and weapons"
    , "- **Supply Depots**: Store components and materials"
    , "- **Repair Facilities**: Fix damaged ships"
    , ""
    , "### Starbase Construction Requirements"
    , "- **Planet**: Must be built over a colonized planet"
    , "- **Resources**: 900 Tritanium, 120 Duranium, 340 Molybdenum"
    , "- **Money**: 100 MegaCredits"
    , "- **Supplies**: 90 supplies"
    , "- **Time**: One turn to complete construction"
    , ""
    , "## Technology Levels"
    , ""
    , "### The Four Tech Categories"
    , "Every starbase has four independent tech levels:"
    , "1. **Hull Tech**: Determines available ship designs"
    , "2. **Engine Tech**: Controls engine types you can build"
    , "3. **Beam Tech**: Sets available beam weapon systems"
    , "4. **Torpedo Tech**: Defines torpedo types you can construct"
    , ""
    , "### Tech Level Advancement"
    , "- **Starting Level**: New starbases begin at Tech 1 in all categories"
    , "- **Upgrade Cost**: Increases exponentially with each level"
    , "  - Tech 1→2: 100 MC"
    , "  - Tech 2→3: 200 MC"
    , "  - Tech 3→4: 300 MC"
    , "  - Tech 4→5: 400 MC"
    , "  - Tech 5→6: 500 MC"
    , "  - Tech 6→7: 600 MC"
    , "  - Tech 7→8: 700 MC"
    , "  - Tech 8→9: 800 MC"
    , "  - Tech 9→10: 900 MC"
    , "- **Total Cost**: Reaching Tech 10 costs 4,500 MC per category"
    , ""
    , "### Native Tech Bonuses"
    , "Certain native races provide free Tech 10 bonuses:"
    , "- **Humanoids**: Free Hull Tech 10"
    , "- **Ghipsoldals**: Free Engine Tech 10"
    , "- **Amphibians**: Free Beam Tech 10"
    , "- **Siliconoids**: Free Torpedo Tech 10"
    , ""
    , "### Tech Strategy"
    , "- **Priority Order**: Usually Hull > Engine > Beam > Torpedo"
    , "- **Minimum Viable**: Tech 5-6 provides most essential designs"
    , "- **Specialization**: Focus different starbases on different roles"
    , "- **Native Bonus**: Always build starbases over tech-bonus natives"
    , ""
    , "## Ship Construction"
    , ""
    , "### Construction Process"
    , "1. **Select Hull**: Choose from available designs at your hull tech"
    , "2. **Configure Components**: Add engines, beams, torpedoes"
    , "3. **Provide Resources**: Supply required materials and money"
    , "4. **Build**: Ship completes in one turn"
    , ""
    , "### Component Storage"
    , "Starbases can pre-build and store components:"
    , "- **Engines**: Store up to 120 engines"
    , "- **Beam Weapons**: Store up to 120 beam weapons"
    , "- **Torpedo Tubes**: Store up to 120 torpedo launchers"
    , "- **Hulls**: Store completed ship hulls"
    , ""
    , "### Build Limitations"
    , "- **One Ship Per Turn**: Each starbase builds one ship maximum"
    , "- **Tech Requirements**: Must meet hull, engine, beam, torpedo tech"
    , "- **Resource Availability**: Need sufficient materials in storage"
    , "- **Queue System**: Subject to game's build queue rules"
    , ""
    , "## Build Queue Systems"
    , ""
    , "### Classic Queue (PBP - Priority Build Points)"
    , "- **Ship Limit**: Hard 500-ship limit galaxy-wide"
    , "- **Priority**: Players with >20 PBP build first"
    , "- **Allocation**: Sequential building based on priority"
    , "- **Strategy**: Save PBP for critical builds"
    , ""
    , "### Production Queue (PQ)"
    , "- **Soft Limit**: 500 ships, then Priority Points required"
    , "- **Flexibility**: Use Priority Points at any starbase"
    , "- **Cost**: Variable PP cost based on ship size/value"
    , "- **Strategy**: More predictable than Classic Queue"
    , ""
    , "### Planetary Production Queue (PPQ)"
    , "- **Planet-Based**: Build allocation based on planet ownership"
    , "- **Proportional**: More planets = more build slots"
    , "- **Current Default**: Used in most Standard games"
    , "- **Strategy**: Expansion directly improves build capacity"
    , ""
    , "### Planets Limit Ships (PLS)"
    , "- **Individual Limits**: Each player has ship cap based on planets"
    , "- **Scaling**: More planets = higher ship limit"
    , "- **Usage**: Beginner games and special formats"
    , "- **Strategy**: Focus on territorial expansion"
    , ""
    , "## Starbase Defense"
    , ""
    , "### Defensive Capabilities"
    , "- **Base Fighters**: 60 fighters maximum"
    , "- **Defense Posts**: 200 maximum (planetary structure)"
    , "- **Beam Weapons**: 20 beam weapons maximum"
    , "- **Starbase Mass**: 900kT for combat calculations"
    , ""
    , "### Fighter Operations"
    , "- **Combat Role**: Fighters attack enemy ships first"
    , "- **Production**: Build fighters at starbase"
    , "- **Cost**: 100 Tritanium, 20 Molybdenum, 3 supplies per fighter"
    , "- **Storage**: Transfer fighters to/from carriers"
    , ""
    , "### Defense Strategy"
    , "- **Minimum Defense**: 20+ fighters deters small raiders"
    , "- **Heavy Defense**: 60 fighters + 200 defense posts"
    , "- **Beam Selection**: Heavy Phasers for maximum damage"
    , "- **Supporting Ships**: Park defending ships at starbase"
    , ""
    , "## Advanced Starbase Operations"
    , ""
    , "### Ship Repair"
    , "- **Automatic**: Damaged ships repair when orbiting starbase"
    , "- **Repair Rate**: Full repair in one turn"
    , "- **Requirements**: Ship must remain stationary"
    , "- **Cost**: Free repair service"
    , ""
    , "### Refitting (Federation Only)"
    , "- **Super Refit**: Federation can refit any ship design"
    , "- **No Tech Limits**: Ignore starbase tech requirements"
    , "- **Strategic Value**: Upgrade old ships to new designs"
    , "- **Resource Cost**: Pay difference in component costs"
    , ""
    , "### Component Trading"
    , "- **Transfer**: Move components between ships and starbase"
    , "- **Storage Management**: Balance component inventory"
    , "- **Supply Lines**: Ship components to other starbases"
    , "- **Emergency Builds**: Pre-position components for rapid construction"
    , ""
    , "## Starbase Placement Strategy"
    , ""
    , "### Strategic Locations"
    , "- **Chokepoints**: Control passage between star clusters"
    , "- **Resource Centers**: Near high-density mining worlds"
    , "- **Native Bonuses**: Over tech-bonus native populations"
    , "- **Defense Positions**: Protect valuable territory"
    , ""
    , "### Economic Considerations"
    , "- **Build Capacity**: More starbases = more ships per turn"
    , "- **Tech Specialization**: Different bases for different ship types"
    , "- **Resource Efficiency**: Minimize component transport costs"
    , "- **Maintenance**: Each base requires ongoing resource investment"
    , ""
    , "### Early vs Late Game"
    , "- **Early Game**: 1-3 starbases for essential needs"
    , "- **Mid Game**: 5-8 starbases for production scaling"
    , "- **Late Game**: 10+ starbases for maximum output"
    , "- **Quality vs Quantity**: High-tech bases vs many basic bases"
    , ""
    , "## Starbase Destruction and Capture"
    , ""
    , "### Vulnerability"
    , "- **Combat Damage**: Enemy ships can destroy starbases"
    , "- **Defense Limits**: Even heavy defenses can be overwhelmed"
    , "- **Strategic Value**: Losing starbase eliminates production"
    , "- **Resource Loss**: Stored components are destroyed"
    , ""
    , "### Protection Methods"
    , "- **Fleet Coverage**: Park defending ships at base"
    , "- **Minefield Defense**: Surround with defensive mines"
    , "- **Early Warning**: Scout networks to detect threats"
    , "- **Backup Bases**: Redundant production capabilities"
    , ""
    , "### Starbase Assault"
    , "- **Target Priority**: Focus on lightly defended bases"
    , "- **Overwhelming Force**: Bring sufficient firepower"
    , "- **Fighter Sweeps**: Clear base fighters first"
    , "- **Follow-up**: Capture or rebuild after destruction"
    , ""
    , "This comprehensive starbase guide covers all aspects of starbase"
    , "operations and strategy in VGA Planets!"
    ]