module Guide.Victory where

victoryGuide :: String
victoryGuide = unlines
    [ "# VGA Planets Victory Conditions Complete Guide"
    , ""
    , "## Victory Overview"
    , ""
    , "### Understanding Victory"
    , "Victory in VGA Planets can be achieved through:"
    , "- **Territorial Control**: Controlling planets and space"
    , "- **Economic Dominance**: Outproducing all opponents"
    , "- **Military Supremacy**: Destroying enemy forces"
    , "- **Diplomatic Success**: Building winning alliances"
    , "- **Specific Conditions**: Meeting game-defined victory rules"
    , ""
    , "### Game End Mechanics"
    , "Games end when:"
    , "- **Victory Condition Met**: A player/alliance achieves victory"
    , "- **Turn Limit Reached**: Fixed-turn games reach conclusion"
    , "- **Player Consensus**: All players agree to end game"
    , "- **Host Decision**: Host ends game due to circumstances"
    , ""
    , "## Standard Victory Conditions"
    , ""
    , "### 1. Diplomatic Planets (Most Common)"
    , "**Requirements:**"
    , "- Control percentage of total planets for 5 consecutive turns"
    , "- Percentage varies based on alliance size:"
    , "  - Solo Victory: 60% of planets"
    , "  - 2-Player Alliance: 70% of planets"
    , "  - 3-Player Alliance: 80% of planets"
    , "  - 4+ Player Alliance: 90% of planets"
    , ""
    , "**Strategy:**"
    , "- Build large fleets for planet capture"
    , "- Form strategic alliances to reduce requirement"
    , "- Hold defensive positions for 5 turns"
    , "- Focus on rapid territorial expansion"
    , ""
    , "### 2. Total Planets"
    , "**Requirements:**"
    , "- Single player must control 50% of all planets"
    , "- Hold for 5 consecutive turns"
    , "- No alliances count toward victory"
    , ""
    , "**Strategy:**"
    , "- Pure military conquest approach"
    , "- Maximize individual economic power"
    , "- Eliminate threats systematically"
    , "- Avoid long-term alliances"
    , ""
    , "### 3. Fixed Turn Victory"
    , "**Requirements:**"
    , "- Game ends on predetermined turn number"
    , "- Winner determined by most planets controlled"
    , "- Ties broken by secondary criteria"
    , ""
    , "**Strategy:**"
    , "- Time-sensitive expansion"
    , "- Late-game planet grabbing"
    , "- Focus on easy targets near deadline"
    , "- Prevent others from gaining planets"
    , ""
    , "### 4. All Planets Victory"
    , "**Requirements:**"
    , "- Single player controls every planet in universe"
    , "- Total galactic domination required"
    , "- Extremely rare victory condition"
    , ""
    , "**Strategy:**"
    , "- Long-term systematic conquest"
    , "- Overwhelming military superiority"
    , "- Eliminate all other players"
    , "- Perfect logistical coordination"
    , ""
    , "### 5. Top Advance Victory"
    , "**Requirements:**"
    , "- Specified number of players must be eliminated"
    , "- Winner has most planets among survivors"
    , "- Gradual elimination format"
    , ""
    , "**Strategy:**"
    , "- Survive elimination phases"
    , "- Build steady expansion"
    , "- Avoid being primary target"
    , "- Opportunistic growth"
    , ""
    , "## Points-Based Victory"
    , ""
    , "### Victory Score System"
    , "**Point Sources:**"
    , "- **Planets**: 1 point per planet owned"
    , "- **Starbases**: 3 points per starbase"
    , "- **Population**: 1 point per 100,000 colonists"
    , "- **Bonus Titles**: Special achievements worth extra points"
    , ""
    , "**Victory Thresholds:**"
    , "- **Standard Games**: 120 points"
    , "- **Epic Games**: 300 points"
    , "- **Custom Games**: Host-defined thresholds"
    , ""
    , "**Strategy:**"
    , "- Balance planet expansion with population growth"
    , "- Build starbases for high point values"
    , "- Pursue bonus titles for extra points"
    , "- Optimize point generation efficiency"
    , ""
    , "### Military Score Victory"
    , "**Point Sources:**"
    , "- Ship combat power"
    , "- Fleet strength ratings"
    , "- Military achievements"
    , "- Combat victories"
    , ""
    , "**Strategy:**"
    , "- Build powerful fleets"
    , "- Engage in combat frequently"
    , "- Win decisive battles"
    , "- Maintain military superiority"
    , ""
    , "## Race-Specific Victory Strategies"
    , ""
    , "### Economic Powerhouses"
    , "**Federation, Privateers, Cyborg**"
    , "- Leverage economic advantages for rapid expansion"
    , "- Build massive fleets through superior income"
    , "- Focus on long-term development"
    , "- Use economic warfare against opponents"
    , ""
    , "### Early Aggressors"
    , "**Lizards, Fascists, Evil Empire**"
    , "- Strike fast in first 30 turns"
    , "- Capture territory before opponents develop"
    , "- Use racial combat bonuses effectively"
    , "- Transition to consolidation mid-game"
    , ""
    , "### Stealth Specialists"
    , "**Birds, Colonies**"
    , "- Use cloaking for surprise attacks"
    , "- Gather intelligence before striking"
    , "- Avoid direct confrontation when possible"
    , "- Strike at weak points in enemy territory"
    , ""
    , "### Defensive Specialists"
    , "**Crystals, Rebels**"
    , "- Control key strategic locations"
    , "- Build strong defensive positions"
    , "- Support aggressive allies"
    , "- Deny territory to enemies"
    , ""
    , "### Technology Races"
    , "**Robots, Cyborg**"
    , "- Focus on advanced ship designs"
    , "- Use technological superiority"
    , "- Build efficient production systems"
    , "- Dominate through superior equipment"
    , ""
    , "## Alliance Victory Strategies"
    , ""
    , "### Alliance Formation"
    , "- **Early Alliances**: Mutual protection and development"
    , "- **Mid-Game Alliances**: Coordinate against threats"
    , "- **Late-Game Alliances**: Push for joint victory"
    , "- **Temporary Alliances**: Short-term tactical cooperation"
    , ""
    , "### Alliance Management"
    , "- **Resource Sharing**: Trade materials and supplies"
    , "- **Military Coordination**: Joint military operations"
    , "- **Territory Division**: Agree on expansion zones"
    , "- **Communication**: Regular diplomatic contact"
    , ""
    , "### Alliance Challenges"
    , "- **Trust Issues**: Preventing betrayal"
    , "- **Resource Disputes**: Fair distribution of gains"
    , "- **Strategy Conflicts**: Different tactical approaches"
    , "- **Victory Sharing**: Deciding final winner"
    , ""
    , "## Victory Timing"
    , ""
    , "### Early Game Victory (Turns 1-30)"
    , "- **Rare but Possible**: Overwhelming early advantage"
    , "- **Requirements**: Major opponent mistakes or dropouts"
    , "- **Strategy**: Hyper-aggressive expansion"
    , "- **Risk**: Vulnerable to counterattack"
    , ""
    , "### Mid-Game Victory (Turns 30-60)"
    , "- **Most Common**: Balanced expansion and development"
    , "- **Requirements**: Steady growth and good positioning"
    , "- **Strategy**: Systematic territorial acquisition"
    , "- **Advantages**: Sustainable growth pattern"
    , ""
    , "### Late Game Victory (Turns 60+)"
    , "- **Attrition Victory**: Outlast opponents"
    , "- **Requirements**: Strong defensive position"
    , "- **Strategy**: Weather enemy attacks, counterattack"
    , "- **Challenges**: Resource depletion, player fatigue"
    , ""
    , "## Victory Prevention"
    , ""
    , "### Stopping Enemy Victory"
    , "- **Alliance Formation**: Unite against victory threat"
    , "- **Targeted Attacks**: Focus on leader's key assets"
    , "- **Resource Denial**: Cut off enemy supply lines"
    , "- **Time Buying**: Delay victory condition fulfillment"
    , ""
    , "### Defensive Strategies"
    , "- **Fortress Worlds**: Heavily defended key planets"
    , "- **Mobile Defense**: Flexible fleet positioning"
    , "- **Scorched Earth**: Deny resources to attackers"
    , "- **Diplomatic Isolation**: Turn others against threat"
    , ""
    , "## Common Victory Mistakes"
    , ""
    , "### Strategic Errors"
    , "- **Premature Declaration**: Announcing victory intentions too early"
    , "- **Overextension**: Expanding faster than you can defend"
    , "- **Alliance Neglect**: Ignoring diplomatic relationships"
    , "- **Resource Mismanagement**: Poor economic planning"
    , ""
    , "### Tactical Mistakes"
    , "- **Poor Defense**: Leaving conquered territory vulnerable"
    , "- **Supply Line Neglect**: Inadequate logistics"
    , "- **Fleet Concentration**: Putting all ships in one location"
    , "- **Intelligence Failure**: Not monitoring enemy capabilities"
    , ""
    , "### Endgame Errors"
    , "- **Victory Rush**: Taking unnecessary risks near victory"
    , "- **Alliance Betrayal**: Breaking partnerships too early"
    , "- **Defensive Relaxation**: Reducing defenses prematurely"
    , "- **Communication Breakdown**: Losing diplomatic contact"
    , ""
    , "This comprehensive victory guide covers all paths to triumph"
    , "in VGA Planets!"
    ]